---
title: "PARAFAC_model_interpretation"
output: html_document
date: "2023-03-27"
---

## Requirements
```{r libraries, include=FALSE}
#library(ggplot2)
library(ggpubr)
#library(compositions)
#library(viridis)
#library(dplyr)
#library(tidyr)
#library(hrbrthemes)
#library(extrafont)
#library(showtext)
#library(vegan)
#library(RColorBrewer)
#library(Polychrome)
#library(multiway)
#library(MatrixCorrelation)
#library(stringr)
#library(asbio)
#library(stringr)
#library(pathview)
#library(gplots)
library(tidyverse)
library(ggrepel)
library(paramGUI)
library(pracma)

source("../R scripts/summary.functions.R")
source("../R scripts/PARAFAC_functions.R")
source("../R scripts/heatmap.2a.R")
set.seed(0)
```

```{r integral functionality}
correctPARAFACloadings = function(model, modeToCorrect){
  A = model[[1]] %>% select(starts_with("Component")) %>% as.matrix()
  B = model[[2]] %>% select(starts_with("Component")) %>% as.matrix()
  C = model[[3]] %>% select(starts_with("Component")) %>% as.matrix()
  
  if(modeToCorrect == 1){
    F = kroneckercol(C, B) %>% as.matrix()
    Ftilde = gramSchmidt(F)$Q
    T = pinv(F) %*% Ftilde
    Atilde = A %*% T
    result = Atilde
  }
  else if(modeToCorrect == 2){
    F = kroneckercol(A, C) %>% as.matrix()
    Ftilde = gramSchmidt(F)$Q
    T = pinv(F) %*% Ftilde
    Btilde = B %*% T
    result = Btilde
  }
  else if(modeToCorrect == 3){
    F = kroneckercol(B, A) %>% as.matrix()
    Ftilde = gramSchmidt(F)$Q
    T = pinv(F) %*% Ftilde
    Ctilde = C %*% T
    result = Ctilde
  }
  
  return(result)
}
```

```{r Import red fluorescence data}
rf_data = read.csv("../0. Raw data input/RFdata.csv")
colnames(rf_data) = c("subject", "id", "fotonr", "day", "group", "RFgroup", "MQH", "SPS(tm)", "Area_delta_R30", "Area_delta_Rmax", "Area_delta_R30_x_Rmax", "gingiva_mean_R_over_G", "gingiva_mean_R_over_G_upper_jaw", "gingiva_mean_R_over_G_lower_jaw")
rf_data = rf_data %>% as_tibble()

rf_data[rf_data$subject == "VSTPHZ", 1] = "VSTPH2"
rf_data[rf_data$subject == "D2VZH0", 1] = "DZVZH0"
rf_data[rf_data$subject == "DLODNN", 1] = "DLODDN"
rf_data[rf_data$subject == "O3VQFX", 1] = "O3VQFQ"
rf_data[rf_data$subject == "F80LGT", 1] = "F80LGF"
rf_data[rf_data$subject == "26QQR0", 1] = "26QQrO"

rf_data2 = read.csv("../0. Raw data input/red_fluorescence_data.csv") %>% as_tibble()
rf_data2 = rf_data2[,c(2,4,181:192)]
rf_data = rf_data %>% left_join(rf_data2)

rf = rf_data %>% select(subject, RFgroup) %>% unique()
```

```{r Import subject metadata}
age_gender = read.csv("../0. Raw data input/20160210 demografische gegevens TIFN2.csv", sep=";")
age_gender = age_gender[2:nrow(age_gender),2:ncol(age_gender)]
age_gender = age_gender %>% as_tibble() %>% filter(onderzoeksgroep == 0) %>% select(naam, leeftijd, geslacht)
colnames(age_gender) = c("subject", "age", "gender")

# Correction for incorrect subject ids
age_gender[age_gender$subject == "VSTPHZ", 1] = "VSTPH2"
age_gender[age_gender$subject == "D2VZH0", 1] = "DZVZH0"
age_gender[age_gender$subject == "DLODNN", 1] = "DLODDN"
age_gender[age_gender$subject == "O3VQFX", 1] = "O3VQFQ"
age_gender[age_gender$subject == "F80LGT", 1] = "F80LGF"
age_gender[age_gender$subject == "26QQR0", 1] = "26QQrO"

age_gender = age_gender %>% arrange(subject)
```

```{r Import microbiome data}
microbiome.raw = read.csv("../0. Raw data input/20221005_wp2/count-table.tsv", sep="\t")
taxa = read.csv("../0. Raw data input/20221005_wp2/taxonomic-classification.tsv", sep="\t")
selectedIndividuals = microbiome.raw %>% as_tibble() %>% filter(group == "control") %>% select(subject) %>% pull %>% unique
```

```{r Import metabolomics data}
metabolomics.raw = read.csv("../0. Raw data input/20221005_wp2/metabolomics.tsv", sep="\t")
metabolomics.raw.notest = metabolomics.raw %>% as_tibble() %>% filter(subject %in% selectedIndividuals)
metabolomics.features = read.csv("../0. Raw data input/20221005_wp2/metabolomics-features.tsv", sep="\t")
```

```{r Import KO mappings}
# Mapping of KO K-number to pathways
KO2pathway = read.csv("../4. Functional microbiome pre-processing/kegg_ko2pathway.txt", sep="\t", header=FALSE) %>% as_tibble()
colnames(KO2pathway) = c("pathway", "KO")
dummy = unlist(strsplit(KO2pathway["KO"] %>% pull, "ko:"))
KO2pathway["KO"] = dummy[dummy != ""]

# Mapping of pathway ID to pathway name
pathway2name = read.csv("../4. Functional microbiome pre-processing/kegg_pathwayNames.txt", sep="\t", header=FALSE) %>% as_tibble()
colnames(pathway2name) = c("pathway", "name")
#pathway2name2 = pathway2name
#pathway2name2$pathway = str_replace(pathway2name$pathway, "map", "ko")

# Mapping of compound to pathway
compound2pathway = read.csv("../4. Functional microbiome pre-processing/kegg_compound2pathway.txt", sep="\t", header=FALSE) %>% as_tibble()
colnames(compound2pathway) = c("pathway", "compound")
dummy = unlist(strsplit(compound2pathway["compound"] %>% pull, "cpd:"))
compound2pathway["compound"] = dummy[dummy != ""]

# Import HOMD
HOMD_mapping = read.csv("../0. Raw data input/homd_result.csv") %>% as_tibble() %>% select(-X)
```

```{r import regular models}
microb_featureNames = c("Kingdom", "Phylum", "Class", "Order", "Family", "Genus", "Species", "representative_sequence", "asv")
metab_featureNames = c("SUPER_PATHWAY","SUB_PATHWAY","BIOCHEMICAL")
microb_days = c(-14,0,2,5,9,14,21)
metab_days = c(0,2,5,9,14)

tongueModel = importPARAFAC("../5. Microbiome modeling/20230605_run/PARAFAC models/Tongue", microb_featureNames, microb_days, "asv")
lowlingModel = importPARAFAC("../5. Microbiome modeling/20230605_run/PARAFAC models/Low_ling", microb_featureNames, microb_days, "asv")
lowinterModel = importPARAFAC("../5. Microbiome modeling/20230605_run/PARAFAC models/Low_inter", microb_featureNames, microb_days, "asv")
uplingModel = importPARAFAC("../5. Microbiome modeling/20230605_run/PARAFAC models/Up_ling", microb_featureNames, microb_days, "asv")
upinterModel = importPARAFAC("../5. Microbiome modeling/20230605_run/PARAFAC models/Up_inter", microb_featureNames, microb_days, "asv")
salivaModel = importPARAFAC("../5. Microbiome modeling/20230605_run/PARAFAC models/Saliva", microb_featureNames, microb_days, "asv")

metabolomicsModel = importPARAFAC("../6. Metabolome modeling/20230605_run/PARAFAC models/Metabolomics", metab_featureNames, metab_days, "BIOCHEMICAL")
```

## Calculating varExp and congruences
```{r calculating all the variance explained - subjects}
varexp_subjects = function(model){
  varExps = apply(model[[4]]^2, 1, function(x){sum(x, na.rm=TRUE)}) / apply(model[[5]]^2, 1,  function(x){sum(x, na.rm=TRUE)})
  result = cbind(model[[1]]$subject, varExps) %>% as_tibble()
  result$varExps = as.numeric(result$varExps)
  colnames(result) = c("subject", "varExps")
  return(result)
}

tongueSubjectVarExps = varexp_subjects(tongueModel)
lowlingSubjectVarExps = varexp_subjects(lowlingModel)
lowinterSubjectVarExps = varexp_subjects(lowinterModel)
uplingSubjectVarExps = varexp_subjects(uplingModel)
upinterSubjectVarExps = varexp_subjects(upinterModel)
salivaSubjectVarExps = varexp_subjects(salivaModel)
metabolomicsSubjectVarExps = varexp_subjects(metabolomicsModel)
```

```{r calculating all the variance explained - features}
varexp_features = function(model, featureNameColumnName){
  varExps = apply(model[[6]]^2, 2, function(x){sum(x, na.rm=TRUE)}) / apply(model[[7]]^2, 2, function(x){sum(x, na.rm=TRUE)})
  result = cbind(model[[2]][featureNameColumnName] %>% pull(), varExps) %>% as_tibble()
  result$varExps = as.numeric(result$varExps)
  colnames(result) = c(featureNameColumnName, "varExps")
  return(result)
}

tongueFeatureVarExps = varexp_features(tongueModel, "asv")
lowlingFeatureVarExps = varexp_features(lowlingModel, "asv")
lowinterFeatureVarExps = varexp_features(lowinterModel, "asv")
uplingFeatureVarExps = varexp_features(uplingModel, "asv")
upinterFeatureVarExps = varexp_features(upinterModel, "asv")
salivaFeatureVarExps = varexp_features(salivaModel, "asv")
metabolomicsFeatureVarExps = varexp_features(metabolomicsModel, "BIOCHEMICAL")
```

```{r calculating all the variance explained - time}
varexp_timepoints = function(model){
  result = 1:nrow(model[[3]])
  
  for(i in 1:nrow(model[[3]])){
    varExp = sum((model[[4]] %>% select(ends_with(paste0("_t",i))))^2, na.rm=TRUE) / sum((model[[5]] %>% select(ends_with(paste0("_t",i))))^2, na.rm=TRUE)
    result[i] = varExp
  }
  
  result = cbind(model[[3]]$days, result) %>% as_tibble()
  colnames(result) = c("days", "varExps")
  return(result)
}

tongueTimeVarExps = varexp_timepoints(tongueModel)
lowlingTimeVarExps = varexp_timepoints(lowlingModel)
lowinterTimeVarExps = varexp_timepoints(lowinterModel)
uplingTimeVarExps = varexp_timepoints(uplingModel)
upinterTimeVarExps = varexp_timepoints(upinterModel)
salivaTimeVarExps = varexp_timepoints(salivaModel)
metabolomicsTimeVarExps = varexp_timepoints(metabolomicsModel)
```

```{r calculating the congruences}
loadCongruences = function(path, nameVector){
  df = read.csv(path, header=FALSE)
  numComponents = ncol(df)
  
  colnames(df) = paste0("Congruence_", 1:numComponents)
  row.names(df) = nameVector
  return(df)
}

tongueSubjectCongruences = loadCongruences("./20230605_run/Tongue_individual_congruence_loadings.csv", tongueModel[[1]]$subject)
lowlingSubjectCongruences = loadCongruences("./20230605_run/Low_ling_individual_congruence_loadings.csv", lowlingModel[[1]]$subject)
lowinterSubjectCongruences = loadCongruences("./20230605_run/Low_inter_individual_congruence_loadings.csv", lowinterModel[[1]]$subject)
uplingSubjectCongruences = loadCongruences("./20230605_run/Up_ling_individual_congruence_loadings.csv", uplingModel[[1]]$subject)
upinterSubjectCongruences = loadCongruences("./20230605_run/Up_inter_individual_congruence_loadings.csv", upinterModel[[1]]$subject)
salivaSubjectCongruences = loadCongruences("./20230605_run/Saliva_individual_congruence_loadings.csv", salivaModel[[1]]$subject)
metabolomicsSubjectCongruences = loadCongruences("./20230605_run/Metabolomics_individual_congruence_loadings.csv", metabolomicsModel[[1]]$subject)

tongueFeatureCongruences = loadCongruences("./20230605_run/Tongue_feature_congruence_loadings.csv", tongueModel[[2]]$asv)
lowlingFeatureCongruences = loadCongruences("./20230605_run/Low_ling_feature_congruence_loadings.csv", lowlingModel[[2]]$asv)
lowinterFeatureCongruences = loadCongruences("./20230605_run/Low_inter_feature_congruence_loadings.csv", lowinterModel[[2]]$asv)
uplingFeatureCongruences = loadCongruences("./20230605_run/Up_ling_feature_congruence_loadings.csv", uplingModel[[2]]$asv)
upinterFeatureCongruences = loadCongruences("./20230605_run/Up_inter_feature_congruence_loadings.csv", upinterModel[[2]]$asv)
salivaFeatureCongruences = loadCongruences("./20230605_run/Saliva_feature_congruence_loadings.csv", salivaModel[[2]]$asv)
metabolomicsFeatureCongruences = loadCongruences("./20230605_run/Metabolomics_feature_congruence_loadings.csv", metabolomicsModel[[2]]$BIOCHEMICAL)
```

## Filtering the features
```{r checking where the important features are - varexp}
featureLoadingLoadingPlot_varExp = function(model, title){
  numComponents = ncol(model[[3]]) - 1
  varExps = apply(model[[6]]^2, 2, function(x){sum(x, na.rm=TRUE)}) / apply(model[[7]]^2, 2, function(x){sum(x, na.rm=TRUE)}) * 100
  Btilde = correctPARAFACloadings(model, 2)
  
  df = model[[2]] %>% mutate(varExp = varExps)
  
  if(numComponents == 1){
    plot = model[[2]] %>% mutate(Component_1=Btilde) %>% ggplot(aes(x=Component_1,y=0,col=varExps)) + geom_point() + scale_color_gradient2(low="blue", mid="purple", high="red", midpoint=50, breaks=seq(0,100,100), limits=c(0,100)) + ggtitle(title)
  }
  else{
    plot = model[[2]] %>% mutate(Component_1=Btilde[,1],Component_2=Btilde[,2]) %>% ggplot(aes(x=Component_1,y=Component_2,col=varExps)) + geom_point() + scale_color_gradient2(low="blue", mid="purple", high="red", midpoint=50, breaks=seq(0,100,100), limits=c(0,100)) + ggtitle(title)
  }
  
  return(plot)
}

a = featureLoadingLoadingPlot_varExp(tongueModel, "tongue")
b = featureLoadingLoadingPlot_varExp(lowlingModel, "lowling")
c = featureLoadingLoadingPlot_varExp(lowinterModel, "lowinter")
d = featureLoadingLoadingPlot_varExp(uplingModel, "upling")
e = featureLoadingLoadingPlot_varExp(upinterModel, "upinter")
f = featureLoadingLoadingPlot_varExp(salivaModel, "saliva")
ggarrange(a,b,c,d,e,f,common.legend=TRUE)

featureLoadingLoadingPlot_varExp(metabolomicsModel, "metabolomics")
```

```{r checking where the important features are - congruences}
congruencePlot_features = function(congruenceOutput, model, title){
  numComponents = ncol(congruenceOutput)
  modelledData = model[[6]]
  inputData = model[[7]]
  
  modelVarExp = sum(modelledData^2, na.rm=TRUE) / sum(inputData^2, na.rm=TRUE)
  featureVarExp = apply(modelledData^2, 2, function(x){sum(x, na.rm=TRUE)}) / apply(inputData^2, 2, function(x){sum(x, na.rm=TRUE)})
  
  square_small = matrix(c(-0.5, -0.5, 0.5, 0.5, -0.5, -0.5, 0.5, 0.5, -0.5, -0.5), nrow=5, ncol=2) %>% as_tibble()
  colnames(square_small) = c("x", "y")
  
  square_large = matrix(c(-1,-1,1,1,-1,-1,1,1,-1,-1), nrow=5, ncol=2) %>% as_tibble()
  colnames(square_large) = c("x", "y")
  
  data = congruenceOutput %>% as_tibble() %>% mutate(normVarExp = (featureVarExp / modelVarExp) - 1)
  
  if(numComponents == 2){
    plot = ggplot() + geom_point(data=data, aes(x=Congruence_1,y=Congruence_2,col=normVarExp)) + xlim(-1,1) + ylim(-1,1) + geom_path(aes(x=x,y=y), data=square_small) + geom_path(aes(x=x,y=y), data=square_large) + ggtitle(title)
  }
  else{
    plot = ggplot() + geom_point(data=data, aes(x=Congruence_1,y=0,col=normVarExp)) + xlim(-1,1) + ylim(-1,1) + geom_vline(xintercept=0.5) + geom_vline(xintercept=-0.5) + geom_vline(xintercept=1) + geom_vline(xintercept=-1) + ggtitle(title)
  }
  
  return(plot)
  
}

a = congruencePlot_features(tongueFeatureCongruences, tongueModel, "tongue")
b = congruencePlot_features(lowlingFeatureCongruences, lowlingModel, "lowling")
c = congruencePlot_features(lowinterFeatureCongruences, lowinterModel, "lowinter")
d = congruencePlot_features(uplingFeatureCongruences, uplingModel, "upling")
e = congruencePlot_features(upinterFeatureCongruences, upinterModel, "upinter")
f = congruencePlot_features(salivaFeatureCongruences, salivaModel, "saliva")
ggarrange(a,b,c,d,e,f)

congruencePlot_features(metabolomicsFeatureCongruences, metabolomicsModel, "metabolomics")
```

```{r filtering the feature mode based on varexp}
filterFeatures = function(model, varExpMultiplier){
  modelVarExp = sum(model[[6]]^2, na.rm=TRUE) / sum(model[[7]]^2, na.rm=TRUE)
  wellModeledFeatures = apply(model[[6]]^2, 2, function(x){sum(x, na.rm=TRUE)}) / apply(model[[7]]^2, 2, function(x){sum(x, na.rm=TRUE)}) > (varExpMultiplier*modelVarExp)
  result = cbind(colnames(model[[6]]), as.logical(as.numeric(wellModeledFeatures))) %>% as_tibble()
  colnames(result) = c("featureName", "keep")
  return(result)
}

microbiomeFilter = 1 # this is one times the varExp of the entire model
metabolomeFilter = 2 # this is two times the varExp of the entire model

tongueFilteredFeatures_varexp = filterFeatures(tongueModel, microbiomeFilter)
lowlingFilteredFeatures_varexp = filterFeatures(lowlingModel, microbiomeFilter)
lowinterFilteredFeatures_varexp = filterFeatures(lowinterModel, microbiomeFilter)
uplingFilteredFeatures_varexp = filterFeatures(uplingModel, microbiomeFilter)
upinterFilteredFeatures_varexp = filterFeatures(upinterModel, microbiomeFilter)
salivaFilteredFeatures_varexp = filterFeatures(salivaModel, microbiomeFilter)

metabolomicsFilteredFeatures_varexp = filterFeatures(metabolomicsModel, metabolomeFilter)
```

```{r plot the filtering result}
featureLoadingLoadingPlot_filtered = function(model, filteredFeatures, title){
  numComponents = ncol(model[[3]]) - 1
  df = model[[2]] %>% left_join(filteredFeatures, by = c("asv" = "featureName"))
  
  if(numComponents == 1){
    plot = df %>% ggplot(aes(x=Component_1,y=0,col=as.factor(keep))) + geom_point() + ggtitle(title)
  }
  else{
    plot = df %>% ggplot(aes(x=Component_1,y=Component_2,col=as.factor(keep))) + geom_point() + ggtitle(title)
  }
  
  return(plot)
}

# Plot the result
a = featureLoadingLoadingPlot_filtered(tongueModel, tongueFilteredFeatures_varexp, "tongue")
b = featureLoadingLoadingPlot_filtered(lowlingModel, lowlingFilteredFeatures_varexp, "lowling")
c = featureLoadingLoadingPlot_filtered(lowinterModel, lowinterFilteredFeatures_varexp, "lowinter")
d = featureLoadingLoadingPlot_filtered(uplingModel, uplingFilteredFeatures_varexp, "upling")
e = featureLoadingLoadingPlot_filtered(upinterModel, upinterFilteredFeatures_varexp, "upinter")
f = featureLoadingLoadingPlot_filtered(salivaModel, salivaFilteredFeatures_varexp, "saliva")
ggarrange(a,b,c,d,e,f, common.legend=TRUE)

model = metabolomicsModel
filteredFeatures = metabolomicsFilteredFeatures_varexp
title = "metabolomics"
numComponents = ncol(model[[3]]) - 1
df = model[[2]] %>% left_join(filteredFeatures, by = c("BIOCHEMICAL" = "featureName"))
df %>% ggplot(aes(x=Component_1,y=Component_2,col=as.factor(keep))) + geom_point() + ggtitle(title)
```

```{r filtering the features based on congruence}
filterByCongruence = function(congruenceOutput, labels, labelName, threshold=0.5){
  numComponents = ncol(congruenceOutput)
  
  if(numComponents == 1){
    keep1 = abs(congruenceOutput[,1]) > threshold
    keep2 = FALSE
  }
  else{
    keep1 = abs(congruenceOutput[,1]) > threshold
    keep2 = abs(congruenceOutput[,2]) > threshold
  }
  
  result = labels %>% as_tibble() %>% mutate(keep = (keep1 | keep2))
  colnames(result) = c(labelName, "keep")
  return(result)
}

microbiomeFilter = 0.4 # this is having a congruence of 0.4 in either component
metabolomeFilter = 0.4 # this is having a congruence of 0.4 in either component

tongueFilteredFeatures_congruence = filterByCongruence(tongueFeatureCongruences, tongueModel[[2]]$asv, "featureName", microbiomeFilter)
lowlingFilteredFeatures_congruence = filterByCongruence(lowlingFeatureCongruences, lowlingModel[[2]]$asv, "featureName", microbiomeFilter)
lowinterFilteredFeatures_congruence = filterByCongruence(lowinterFeatureCongruences, lowinterModel[[2]]$asv, "featureName", microbiomeFilter)
uplingFilteredFeatures_congruence = filterByCongruence(uplingFeatureCongruences, uplingModel[[2]]$asv, "featureName", microbiomeFilter)
upinterFilteredFeatures_congruence = filterByCongruence(upinterFeatureCongruences, upinterModel[[2]]$asv, "featureName", microbiomeFilter)
salivaFilteredFeatures_congruence = filterByCongruence(salivaFeatureCongruences, salivaModel[[2]]$asv, "featureName", microbiomeFilter)
metabolomicsFilteredFeatures_congruence = filterByCongruence(metabolomicsFeatureCongruences, metabolomicsModel[[2]]$BIOCHEMICAL, "featureName", metabolomeFilter)
```

```{r plot the filtering result}
featureLoadingLoadingPlot = function(model, title){
  numComponents = ncol(model[[3]]) - 1
  Btilde = correctPARAFACloadings(model,2)
  
  if(numComponents == 1){
    plot = model[[2]] %>% mutate(Component_1=Btilde) %>% ggplot(aes(x=Component_1,y=0)) + geom_point() + ggtitle(title)
  }
  else{
    plot = model[[2]] %>% mutate(Component_1=Btilde[,1], Component_2=Btilde[,2]) %>%  ggplot(aes(x=Component_1,y=Component_2)) + geom_point() + ggtitle(title)
  }
  
  return(plot)
}

featureLoadingLoadingPlot_filtered = function(model, filteredFeatures, title){
  numComponents = ncol(model[[3]]) - 1
  df = model[[2]] %>% left_join(filteredFeatures, by = c("asv" = "featureName"))
  
  if(numComponents == 1){
    plot = df %>% ggplot(aes(x=Component_1,y=0,col=as.factor(keep))) + geom_point() + ggtitle(title)
  }
  else{
    plot = df %>% ggplot(aes(x=Component_1,y=Component_2,col=as.factor(keep))) + geom_point() + ggtitle(title)
  }
  
  return(plot)
}

# Plot the result
a = featureLoadingLoadingPlot_filtered(tongueModel, tongueFilteredFeatures_congruence, "tongue")
b = featureLoadingLoadingPlot_filtered(lowlingModel, lowlingFilteredFeatures_congruence, "lowling")
c = featureLoadingLoadingPlot_filtered(lowinterModel, lowinterFilteredFeatures_congruence, "lowinter")
d = featureLoadingLoadingPlot_filtered(uplingModel, uplingFilteredFeatures_congruence, "upling")
e = featureLoadingLoadingPlot_filtered(upinterModel, upinterFilteredFeatures_congruence, "upinter")
f = featureLoadingLoadingPlot_filtered(salivaModel, salivaFilteredFeatures_congruence, "saliva")
ggarrange(a,b,c,d,e,f, common.legend=TRUE)

model = metabolomicsModel
filteredFeatures = metabolomicsFilteredFeatures_congruence
title = "metabolomics"
numComponents = ncol(model[[3]]) - 1
df = model[[2]] %>% left_join(filteredFeatures, by = c("BIOCHEMICAL" = "featureName"))
df %>% ggplot(aes(x=Component_1,y=Component_2,col=as.factor(keep))) + geom_point() + ggtitle(title)
```

```{r combining the filters}
tongueFilteredFeatures = tongueFilteredFeatures_varexp %>% mutate(keep = (tongueFilteredFeatures_varexp$keep==TRUE & tongueFilteredFeatures_congruence$keep==TRUE))
lowlingFilteredFeatures = lowlingFilteredFeatures_varexp %>% mutate(keep = (lowlingFilteredFeatures_varexp$keep==TRUE & lowlingFilteredFeatures_congruence$keep==TRUE))
lowinterFilteredFeatures = lowinterFilteredFeatures_varexp %>% mutate(keep = (lowinterFilteredFeatures_varexp$keep==TRUE & lowinterFilteredFeatures_congruence$keep==TRUE))
uplingFilteredFeatures = uplingFilteredFeatures_varexp %>% mutate(keep = (uplingFilteredFeatures_varexp$keep==TRUE & uplingFilteredFeatures_congruence$keep==TRUE))
upinterFilteredFeatures = upinterFilteredFeatures_varexp %>% mutate(keep = (upinterFilteredFeatures_varexp$keep==TRUE & upinterFilteredFeatures_congruence$keep==TRUE))
salivaFilteredFeatures = salivaFilteredFeatures_varexp %>% mutate(keep = (salivaFilteredFeatures_varexp$keep==TRUE & salivaFilteredFeatures_congruence$keep==TRUE))

metabolomicsFilteredFeatures = metabolomicsFilteredFeatures_varexp %>% mutate(keep = (metabolomicsFilteredFeatures_varexp$keep==TRUE & metabolomicsFilteredFeatures_congruence$keep==TRUE))
```

```{r plot the result of combined filtering}
# Plot the result
a = featureLoadingLoadingPlot_filtered(tongueModel, tongueFilteredFeatures, "tongue")
b = featureLoadingLoadingPlot_filtered(lowlingModel, lowlingFilteredFeatures, "lowling")
c = featureLoadingLoadingPlot_filtered(lowinterModel, lowinterFilteredFeatures, "lowinter")
d = featureLoadingLoadingPlot_filtered(uplingModel, uplingFilteredFeatures, "upling")
e = featureLoadingLoadingPlot_filtered(upinterModel, upinterFilteredFeatures, "upinter")
f = featureLoadingLoadingPlot_filtered(salivaModel, salivaFilteredFeatures, "saliva")
ggarrange(a,b,c,d,e,f, common.legend=TRUE)

model = metabolomicsModel
filteredFeatures = metabolomicsFilteredFeatures
title = "metabolomics"
numComponents = ncol(model[[3]]) - 1
df = model[[2]] %>% left_join(filteredFeatures, by = c("BIOCHEMICAL" = "featureName"))
df %>% ggplot(aes(x=Component_1,y=Component_2,col=as.factor(keep))) + geom_point() + ggtitle(title)
```

```{r checking the remaining feature names}
labelledFilteredFeaturesPlot = function(model, filteredFeatures, title){
  numComponents = ncol(model[[3]]) - 1
  df = model[[2]] %>% left_join(filteredFeatures, by=c("asv" = "featureName")) %>% filter(keep==TRUE) %>% left_join(HOMD_mapping)
  
  if(numComponents == 1){
    plot = df %>% ggplot(aes(x=Component_1, y=0, col=as.factor(Phylum), label=homd)) + geom_point() + geom_text_repel(col="black") + ggtitle(title)
  }
  else{
    plot = df %>% ggplot(aes(x=Component_1, y=Component_2, col=as.factor(Phylum), label=homd)) + geom_point() + geom_text_repel(col="black", max.overlaps=50) + ggtitle(title)
  }
  
  return(plot)
}

labelledFilteredFeaturesPlot(tongueModel, tongueFilteredFeatures, "tongue")
labelledFilteredFeaturesPlot(lowlingModel, lowlingFilteredFeatures, "lowling")
labelledFilteredFeaturesPlot(lowinterModel, lowinterFilteredFeatures, "lowinter")
labelledFilteredFeaturesPlot(uplingModel, uplingFilteredFeatures, "upling")
labelledFilteredFeaturesPlot(upinterModel, upinterFilteredFeatures, "upinter")
labelledFilteredFeaturesPlot(salivaModel, salivaFilteredFeatures, "saliva")

model = metabolomicsModel
filteredFeatures = metabolomicsFilteredFeatures
df = model[[2]] %>% left_join(filteredFeatures, by=c("BIOCHEMICAL" = "featureName")) %>% filter(keep==TRUE)
plot = df %>% ggplot(aes(x=Component_1, y=Component_2, col=as.factor(SUPER_PATHWAY), label=BIOCHEMICAL)) + geom_point() + geom_text_repel(col="black") + ggtitle("Metabolomics")
print(plot)
```

```{r put feature locations onto orthonormal basis}
biplotAcrossTime = function(model, filteredFeatures, titleString){
  A = model[[1]] %>% select(starts_with("Component")) %>% as.matrix()
  B = model[[2]] %>% select(starts_with("Component")) %>% as.matrix()
  C = model[[3]] %>% select(starts_with("Component")) %>% as.matrix()
  
  F = kroneckercol(A,C)
  Btilde = gramSchmidt(B)$Q
  T = pinv(B) %*% Btilde
  Ftilde = F %*% T
  
  numComponents = ncol(model[[3]]) - 1
  ssqResiduals_subjects = (model[[5]] - model[[4]])^2 %>% as_tibble() %>% rowSums(., na.rm=TRUE) %>% as_tibble() %>% mutate(subject=model[[1]]$subject) %>% mutate(ssqResidualsSubjects = value) %>% select(-value)
  modelVarExp = round(sum(model[[4]]^2, na.rm=TRUE) / sum(model[[5]]^2, na.rm=TRUE) * 100, digits=1)
  
  Ftilde = Ftilde %>% as_tibble() %>% mutate(subject = rep(model[[1]]$subject,each=nrow(model[[3]])), timepoint = rep(model[[3]]$days, nrow(model[[1]]))) %>% left_join(ssqResiduals_subjects)

  if(numComponents == 2){
    colnames(Ftilde) = c("Component_1", "Component_2", "subject", "timepoint", "ssqResiduals")
    
    enlargingFactor = mean(apply(Ftilde[,1:2], 2, max) / apply(Btilde, 2, max))
    Btilde = Btilde * enlargingFactor
    Btilde = Btilde %>% as_tibble() %>% mutate(featureName = model[[2]]$asv) %>% left_join(filteredFeatures) %>% filter(keep==TRUE) %>% select(V1,V2)
    colnames(Btilde) = c("Component_1", "Component_2")
  }
  else{
    colnames(Ftilde) = c("Component_1", "subject", "timepoint", "ssqResiduals")
    enlargingFactor = apply(Ftilde[,1], 2, max) / apply(Btilde, 2, max)
    Btilde = Btilde * enlargingFactor
    Btilde = Btilde %>% as_tibble() %>% mutate(featureName = model[[2]]$asv) %>% left_join(filteredFeatures) %>% filter(keep==TRUE) %>% select(V1)
    colnames(Btilde) = c("Component_1")
    Btilde = Btilde %>% mutate(Component_2 = 0)
    
    set.seed(1)
    jitterpoints = rep(jitter(rep(0, nrow(model[[1]]))), each=nrow(model[[3]]))
    Ftilde = Ftilde %>% mutate(Component_2=jitterpoints)
  }
  
  Btilde = Btilde %>% mutate(asv = filteredFeatures %>% filter(keep==TRUE) %>% select(featureName) %>% pull()) %>% left_join(HOMD_mapping)
  
  
  ggplot() + 
    geom_segment(data = Btilde, aes(x=0,y=0,xend=Component_1,yend=Component_2), arrow=arrow(angle=15, length=unit(0.10, "inches")), color="red", alpha=0.75) +
    geom_point(data = Ftilde %>% filter(timepoint==-14), aes(x=Component_1, y=Component_2, group=as.factor(subject), col=ssqResiduals)) +
    geom_path(data = Ftilde, aes(x=Component_1, y=Component_2, group=as.factor(subject), col=ssqResiduals), arrow = arrow(angle = 15, length=unit(0.10, "inches"), type = "closed")) +
    geom_label_repel(data = Btilde, aes(x=Component_1, y=Component_2, label=homd), max.overlaps=5, segment.color=NA) +
    scale_x_continuous(name="Component 1 (scores)",
                       sec.axis=sec_axis(name="Component 1 (loadings)",~./enlargingFactor)) +
    scale_y_continuous(name="Component 2 (scores)",
                       sec.axis=sec_axis(name="Component 2 (loadings)",~./enlargingFactor)) +
    scale_colour_gradient("Sum of squared residuals (subjects)", limits=c(0,1200), low="black", high="white") +
    theme(axis.text.y.right=element_text(colour="red"),
          axis.title.y.right=element_text(colour="red"),
          axis.title.x.top=element_text(colour="red"),
          axis.text.x.top=element_text(colour="red")) +
    ggtitle(paste0(titleString, " (", modelVarExp, "%)"))
}

biplotAcrossTime2 = function(model, filteredFeatures, titleString){
  A = model[[1]] %>% select(starts_with("Component")) %>% as.matrix()
  B = model[[2]] %>% select(starts_with("Component")) %>% as.matrix()
  C = model[[3]] %>% select(starts_with("Component")) %>% as.matrix()
  
  F = kroneckercol(A,C)
  Btilde = gramSchmidt(B)$Q
  T = pinv(B) %*% Btilde
  Ftilde = F %*% T
  
  numComponents = ncol(model[[3]]) - 1
  
  if(numComponents == 2){
    enlargingFactor = mean(apply(Ftilde, 2, max) / apply(Btilde, 2, max))
    Btilde = Btilde * enlargingFactor
    
    Ftilde = Ftilde %>% as_tibble() %>% mutate(subject = rep(model[[1]]$subject,each=nrow(model[[3]])), timepoint = rep(model[[3]]$days, nrow(model[[1]]))) %>% group_by(subject) %>% summarise(m1=mean(V1),m2=mean(V2))
    featureLabels = model[[2]] %>% mutate(featureName = asv) %>% left_join(filteredFeatures) %>% filter(keep==TRUE)
    featureLabels[is.na(featureLabels$Species), "Species"] = "sp." 
    featureLabels = featureLabels %>% mutate(name=paste0(Genus," ",Species)) %>% select(name) %>% pull
    Btilde = Btilde %>% as_tibble() %>% mutate(featureName = model[[2]]$asv) %>% left_join(filteredFeatures) %>% filter(keep==TRUE) %>% select(V1,V2)
    colnames(Btilde) = c("Component_1", "Component_2")
  
    ggplot() + 
      geom_point(data = Ftilde, aes(x=m1, y=m2)) +
      geom_segment(data = Btilde, aes(x=0,y=0,xend=Component_1,yend=Component_2), arrow=arrow(), color="red") +
      geom_text_repel(data = Btilde, aes(x=Component_1, y=Component_2, label=featureLabels, col="red"), max.overlaps=5, segment.color=NA) +
      scale_x_continuous(name="Component_1",sec.axis=sec_axis(name="Component_1",~./enlargingFactor)) +
      scale_y_continuous(name="Component_2",sec.axis=sec_axis(name="Component_2",~./enlargingFactor)) +
      ggtitle(titleString) +
      theme_classic() +
      theme(legend.position="none", axis.text.y.right=element_text(colour="red"), axis.title.y.right=element_text(colour="red"), axis.title.x.top=element_text(colour="red"), axis.text.x.top=element_text(colour="red"))
      
  }
  else{
    enlargingFactor = apply(Ftilde, 2, max) / apply(Btilde, 2, max)
    Btilde = Btilde * enlargingFactor
    
    Ftilde = Ftilde %>% as_tibble() %>% mutate(subject = rep(model[[1]]$subject,each=nrow(model[[3]])), timepoint = rep(model[[3]]$days, nrow(model[[1]]))) %>% group_by(subject) %>% summarise(m1=mean(V1))
    featureLabels = model[[2]] %>% mutate(featureName = asv) %>% left_join(filteredFeatures) %>% filter(keep==TRUE) %>% mutate(name=paste0(Genus,"_",Species)) %>% select(name) %>% pull()
    Btilde = Btilde %>% as_tibble() %>% mutate(featureName = model[[2]]$asv) %>% left_join(filteredFeatures) %>% filter(keep==TRUE) %>% select(V1)
    colnames(Btilde) = c("Component_1")
  
    ggplot() + 
      geom_point(data = Ftilde, aes(x=m1, y=0)) +
      geom_segment(data = Btilde, aes(x=0,y=0,xend=Component_1,yend=0), arrow=arrow(), color="red") +
      geom_text_repel(data = Btilde, aes(x=Component_1, y=0, label=featureLabels, col="red")) +
      scale_x_continuous(name="Component_1",sec.axis=sec_axis(name="Component_1",~./enlargingFactor)) +
      scale_y_continuous(name="Component_2",sec.axis=sec_axis(name="Component_2",~./enlargingFactor)) +
      ggtitle(titleString) +
      theme_classic() +
      theme(legend.position="none", axis.text.y.right=element_text(colour="red"), axis.title.y.right=element_text(colour="red"), axis.title.x.top=element_text(colour="red"), axis.text.x.top=element_text(colour="red"))
  }
  
}

a = biplotAcrossTime(tongueModel, tongueFilteredFeatures, "Tongue")
b = biplotAcrossTime(lowlingModel, lowlingFilteredFeatures, "Lower jaw, lingual")
c = biplotAcrossTime(lowinterModel, lowinterFilteredFeatures, "Lower jaw, interproximal")
d = biplotAcrossTime(uplingModel, uplingFilteredFeatures, "Upper jaw, lingual")
e = biplotAcrossTime(upinterModel, upinterFilteredFeatures, "Upper jaw, interproximal")
f = biplotAcrossTime(salivaModel, salivaFilteredFeatures, "Saliva")

print(a)
print(b)
print(c)
print(d)
print(e)
print(f)
fig = ggarrange(a + theme(axis.title.y.right=element_blank(),axis.title.x.top=element_blank(),axis.title.y.left=element_blank(),axis.title.x.bottom=element_blank()),
                b + theme(axis.title.y.right=element_blank(),axis.title.x.top=element_blank(),axis.title.y.left=element_blank(),axis.title.x.bottom=element_blank()),
                c + theme(axis.title.y.right=element_blank(),axis.title.x.top=element_blank(),axis.title.y.left=element_blank(),axis.title.x.bottom=element_blank()),
                d + theme(axis.title.y.right=element_blank(),axis.title.x.top=element_blank(),axis.title.y.left=element_blank(),axis.title.x.bottom=element_blank()),
                e + theme(axis.title.y.right=element_blank(),axis.title.x.top=element_blank(),axis.title.y.left=element_blank(),axis.title.x.bottom=element_blank()),
                f + theme(axis.title.y.right=element_blank(),axis.title.x.top=element_blank(),axis.title.y.left=element_blank(),axis.title.x.bottom=element_blank()),
                nrow=3, ncol=2, common.legend=TRUE)
```

```{r proof of individual vs time variation explained}
plotAllVarExps = function(model, subjectVarExps, featureVarExps, timeVarExps, titleString){
  modelVarExp = sum(model[[6]]^2, na.rm=TRUE) / sum(model[[7]]^2, na.rm=TRUE)
  
  subjectVarExps = subjectVarExps %>% select(-subject) %>% mutate(type="subject", varExps = varExps * 100)
  featureVarExps = featureVarExps %>% select(-asv) %>% mutate(type="feature", varExps = varExps * 100)
  timeVarExps = timeVarExps %>% select(-days) %>% mutate(type="time", varExps = varExps * 100)
  df = rbind(subjectVarExps, featureVarExps, timeVarExps) %>% as_tibble()
  
  df %>% ggplot(aes(x=as.factor(type),y=varExps,fill=as.factor(type))) + geom_boxplot() + geom_hline(yintercept=modelVarExp*100,col="red") + ggtitle(paste0(titleString, " (", round(modelVarExp*100,2), "%)")) + xlab("") + ylab("Variance explained (%)") + ylim(0,100)
}

a = plotAllVarExps(tongueModel, tongueSubjectVarExps, tongueFeatureVarExps, tongueTimeVarExps, "Tongue")
b = plotAllVarExps(lowlingModel, lowlingSubjectVarExps, lowlingFeatureVarExps, lowlingTimeVarExps, "Lower jaw, lingual")
c = plotAllVarExps(lowinterModel, lowinterSubjectVarExps, lowinterFeatureVarExps, lowinterTimeVarExps, "Lower jaw, interproximal")
d = plotAllVarExps(uplingModel, uplingSubjectVarExps, uplingFeatureVarExps, uplingTimeVarExps, "Upper jaw, lingual")
e = plotAllVarExps(upinterModel, upinterSubjectVarExps, upinterFeatureVarExps, upinterTimeVarExps, "Upper jaw, interproximal")
f = plotAllVarExps(salivaModel, salivaSubjectVarExps, salivaFeatureVarExps, salivaTimeVarExps, "Saliva")
ggarrange(a,b,c,d,e,f, nrow=3, ncol=2, common.legend=TRUE)
```

```{r experimental plot for intra and inter individual variation}
tongueModelVarExp = sum(tongueModel[[6]]^2, na.rm=TRUE) / sum(tongueModel[[7]]^2, na.rm=TRUE)
lowlingModelVarExp = sum(lowlingModel[[6]]^2, na.rm=TRUE) / sum(lowlingModel[[7]]^2, na.rm=TRUE)
lowinterModelVarExp = sum(lowinterModel[[6]]^2, na.rm=TRUE) / sum(lowinterModel[[7]]^2, na.rm=TRUE)
uplingModelVarExp = sum(uplingModel[[6]]^2, na.rm=TRUE) / sum(uplingModel[[7]]^2, na.rm=TRUE)
upinterModelVarExp = sum(upinterModel[[6]]^2, na.rm=TRUE) / sum(upinterModel[[7]]^2, na.rm=TRUE)
salivaModelVarExp = sum(salivaModel[[6]]^2, na.rm=TRUE) / sum(salivaModel[[7]]^2, na.rm=TRUE)

subjectVarExps = rbind(tongueSubjectVarExps %>%
                         mutate(varExps = varExps / tongueModelVarExp),
                       lowlingSubjectVarExps %>%
                         mutate(varExps = varExps / lowlingModelVarExp),
                       lowinterSubjectVarExps %>%
                         mutate(varExps = varExps / lowinterModelVarExp),
                       uplingSubjectVarExps %>%
                         mutate(varExps = varExps / uplingModelVarExp),
                       upinterSubjectVarExps %>%
                         mutate(varExps = varExps / upinterModelVarExp),
                       salivaSubjectVarExps %>%
                         mutate(varExps = varExps / salivaModelVarExp)) %>%
  as_tibble() %>%
  mutate(niche = rep(c("tongue", "lowling", "lowinter", "upling", "upinter","saliva"), each=41))

subjectResult = subjectVarExps %>% group_by(as.factor(niche)) %>% summarize(m=median(varExps), s=mad(varExps))
colnames(subjectResult) = c("niche", "sMean", "sSd")

timeVarExps = rbind(tongueTimeVarExps %>%
                         mutate(varExps = varExps / tongueModelVarExp),
                       lowlingTimeVarExps %>%
                         mutate(varExps = varExps / lowlingModelVarExp),
                       lowinterTimeVarExps %>%
                         mutate(varExps = varExps / lowinterModelVarExp),
                       uplingTimeVarExps %>%
                         mutate(varExps = varExps / uplingModelVarExp),
                       upinterTimeVarExps %>%
                         mutate(varExps = varExps / upinterModelVarExp),
                       salivaTimeVarExps %>%
                         mutate(varExps = varExps / salivaModelVarExp)) %>%
  as_tibble() %>%
  mutate(niche = rep(c("tongue", "lowling", "lowinter", "upling", "upinter","saliva"), each=7))

timeResult = timeVarExps %>% group_by(as.factor(niche)) %>% summarize(m=median(varExps), mad=sd(varExps))
colnames(timeResult) = c("niche", "tMean", "tSd")

df = subjectResult %>% left_join(timeResult)
df %>% ggplot(aes(x=sMean,y=tMean,xmin=sMean-sSd,xmax=sMean+sSd,ymin=tMean-tSd,ymax=tMean+tSd, label=niche)) + geom_point() + geom_abline(slope=1,intercept=0) + geom_errorbar() + geom_errorbarh() + geom_label_repel()

a=subjectVarExps %>% ggplot(aes(x=as.factor(niche),y=varExps)) + geom_boxplot(width=0.25) + geom_hline(yintercept=1,col="red") + ggtitle("Intra-individual variation explained") + xlab("Sampling location") + ylab("Normalized variance explained")
b=timeVarExps %>% ggplot(aes(x=as.factor(niche),y=varExps)) + geom_boxplot(width=0.25) + geom_hline(yintercept=1,col="red") + ggtitle("Inter-individual variation explained") + xlab("Sampling location") + ylab("Normalized variance explained")
ggarrange(a,b,nrow=2)

rbind(subjectVarExps %>% mutate(type="intra") %>% select(-subject), timeVarExps %>% mutate(type="inter") %>% select(-days)) %>% ggplot(aes(x=as.factor(type),y=varExps,fill=as.factor(type))) + facet_grid(~as.factor(niche)) + geom_boxplot(outlier.shape=NA) + ylim(0,3.5)

rbind(subjectVarExps %>% mutate(type="intra") %>% select(-subject), timeVarExps %>% mutate(type="inter") %>% select(-days)) %>% ggplot(aes(x=as.factor(type),y=varExps)) + geom_violin() + geom_boxplot(width=0.15) + stat_compare_means(method="wilcox.test", method.args=list(alternative="greater")) + ylim(0, 7) + ylab("Normalized variance explained") + xlab("Type of variation")
```

# Clustering diagnostics
```{r diagnostics for clustering}
library(cluster)
library(factoextra)

plotClusteringDiagnostics = function(model, filteredFeatures){
  selectedFeatures = filteredFeatures %>% filter(keep==TRUE) %>% select(featureName) %>% pull()
  Xhat = model[[6]] %>% select(all_of(selectedFeatures))
  
  a = fviz_nbclust(t(Xhat), pam, method="wss")
  b = fviz_nbclust(t(Xhat), pam, method="silhouette")
  c = fviz_nbclust(t(Xhat), pam, method="gap_stat")
  return(list(a,b,c))
}

p1 = plotClusteringDiagnostics(tongueModel, tongueFilteredFeatures)
p2 = plotClusteringDiagnostics(lowlingModel, lowlingFilteredFeatures)
p3 = plotClusteringDiagnostics(lowinterModel, lowinterFilteredFeatures)
p4 = plotClusteringDiagnostics(uplingModel, uplingFilteredFeatures)
p5 = plotClusteringDiagnostics(upinterModel, upinterFilteredFeatures)
p6 = plotClusteringDiagnostics(salivaModel, salivaFilteredFeatures)
ggarrange(p1[[1]], p2[[1]], p3[[1]], p4[[1]], p5[[1]], p6[[1]], p1[[2]], p2[[2]], p3[[2]], p4[[2]], p5[[2]], p6[[2]], p1[[3]], p2[[3]], p3[[3]], p4[[3]], p5[[3]], p6[[3]], nrow=3, ncol=6)

p7 = plotClusteringDiagnostics(metabolomicsModel, metabolomicsFilteredFeatures)
p7[[1]]
p7[[2]]
p7[[3]]
```

## Defining the feature groups
```{r KNN clustering of the filtered features}
clusterFeatureLoadings_filtered = function(model, filteredFeatures, numClusters){
  numComponents = ncol(model[[3]]) - 1
  Btilde = correctPARAFACloadings(model, 2)
  colnames(Btilde) = paste0("Component_", 1:numComponents)
  df = Btilde %>% as_tibble() %>% mutate(asv=model[[2]]$asv) %>% left_join(filteredFeatures, by = c("asv" = "featureName")) %>% filter(keep == 1)
  result = df
  
  selectedFeatures = filteredFeatures %>% filter(keep==TRUE) %>% select(featureName) %>% pull()
  Xhat = model[[6]] %>% select(all_of(selectedFeatures))
  
  set.seed(1)
  result$group = pam(t(Xhat), numClusters, nstart=50)$cluster
  result = result %>% left_join(HOMD_mapping)
  
  return(result)
}

plotFeatureClustering = function(model, filteredFeatures, featureClustering, title){
  numComponents = ncol(model[[3]]) - 1
  Btilde = correctPARAFACloadings(model, 2)
  Btilde = Btilde[filteredFeatures$keep == TRUE,]
  
  if(numComponents==1){
    plot = featureClustering %>% mutate(Component_1 = Btilde) %>% ggplot(aes(x=Component_1,y=0,col=as.factor(group))) + geom_point() + geom_vline(xintercept=0, linetype=2) + ggtitle(title) + xlab("Component 1") + ylab("Component 2") + scale_color_discrete(name="Cluster")
  }
  else{
    plot = featureClustering %>% mutate(Component_1 = Btilde[,1], Component_2 = Btilde[,2]) %>% ggplot(aes(x=Component_1,y=Component_2,col=as.factor(group))) + geom_point() + geom_vline(xintercept=0, linetype=2) + geom_hline(yintercept=0, linetype=2) + ggtitle(title) + xlab("Component 1") + ylab("Component 2") + scale_color_discrete(name="Cluster")
  }
  
  return(plot)
}

plotFeatureClustering_meta = function(model, filteredFeatures, featureClustering, title){
  numComponents = ncol(model[[3]]) - 1
  Btilde = correctPARAFACloadings(model, 2)
  Btilde = Btilde[filteredFeatures$keep == TRUE,]
  
  if(numComponents==1){
    featureClustering = featureClustering %>% left_join(model[[2]] %>% select(-Component_1))
    plot = featureClustering %>% mutate(Component_1 = Btilde) %>% ggplot(aes(x=Component_1,y=0,col=as.factor(Phylum))) + geom_point() + geom_vline(xintercept=0, linetype=2) + ggtitle(title)
  }
  else{
    featureClustering = featureClustering %>% left_join(model[[2]] %>% select(-Component_1,-Component_2))
    plot = featureClustering %>% mutate(Component_1 = Btilde[,1], Component_2 = Btilde[,2]) %>% ggplot(aes(x=Component_1,y=Component_2,col=as.factor(Phylum))) + geom_point() + geom_vline(xintercept=0, linetype=2) + geom_hline(yintercept=0, linetype=2) + ggtitle(title)
  }
  
  return(plot)
}

tongueFeatureClustering = clusterFeatureLoadings_filtered(tongueModel, tongueFilteredFeatures, 2)
a = plotFeatureClustering(tongueModel, tongueFilteredFeatures, tongueFeatureClustering, "tongue")
b = plotFeatureClustering_meta(tongueModel, tongueFilteredFeatures, tongueFeatureClustering, "tongue")
ggarrange(a,b)

lowlingFeatureClustering = clusterFeatureLoadings_filtered(lowlingModel, lowlingFilteredFeatures, 2)
a = plotFeatureClustering(lowlingModel, lowlingFilteredFeatures, lowlingFeatureClustering, "lowling")
b = plotFeatureClustering_meta(lowlingModel, lowlingFilteredFeatures, lowlingFeatureClustering, "lowling")
ggarrange(a,b)

lowinterFeatureClustering = clusterFeatureLoadings_filtered(lowinterModel, lowinterFilteredFeatures, 2)
a = plotFeatureClustering(lowinterModel, lowinterFilteredFeatures, lowinterFeatureClustering, "lowinter")
b = plotFeatureClustering_meta(lowinterModel, lowinterFilteredFeatures, lowinterFeatureClustering, "lowinter")
ggarrange(a,b)

uplingFeatureClustering = clusterFeatureLoadings_filtered(uplingModel, uplingFilteredFeatures, 2)
a = plotFeatureClustering(uplingModel, uplingFilteredFeatures, uplingFeatureClustering, "upling")
b = plotFeatureClustering_meta(uplingModel, uplingFilteredFeatures, uplingFeatureClustering, "upling")
ggarrange(a,b)

upinterFeatureClustering = clusterFeatureLoadings_filtered(upinterModel, upinterFilteredFeatures, 4)
a = plotFeatureClustering(upinterModel, upinterFilteredFeatures, upinterFeatureClustering, "upinter")
b = plotFeatureClustering_meta(upinterModel, upinterFilteredFeatures, upinterFeatureClustering, "upinter")
ggarrange(a,b)

salivaFeatureClustering = clusterFeatureLoadings_filtered(salivaModel, salivaFilteredFeatures, 2)
a = plotFeatureClustering(salivaModel, salivaFilteredFeatures, salivaFeatureClustering, "saliva")
b = plotFeatureClustering_meta(salivaModel, salivaFilteredFeatures, salivaFeatureClustering, "saliva")
ggarrange(a,b)

model = metabolomicsModel
filteredFeatures = metabolomicsFilteredFeatures
numClusters = 2

numComponents = ncol(model[[3]]) - 1
Btilde = correctPARAFACloadings(model, 2)
colnames(Btilde) = paste0("Component_", 1:numComponents)
df = Btilde %>% as_tibble() %>% mutate(BIOCHEMICAL=model[[2]]$BIOCHEMICAL) %>% left_join(filteredFeatures, by = c("BIOCHEMICAL" = "featureName")) %>% filter(keep == 1)
result = df
df = df %>% select(Component_1, Component_2) %>% as.matrix()
set.seed(1)
result$group = pam(df, numClusters, nstart=50)$cluster

metabolomicsFeatureClustering = result

plotFeatureClustering(metabolomicsModel, metabolomicsFilteredFeatures, metabolomicsFeatureClustering, "metabolomics")
```

```{r extra plot for paper}
a = plotFeatureClustering(tongueModel, tongueFilteredFeatures, tongueFeatureClustering, "tongue")
b = plotFeatureClustering(lowlingModel, lowlingFilteredFeatures, lowlingFeatureClustering, "lowling")
c = plotFeatureClustering(lowinterModel, lowinterFilteredFeatures, lowinterFeatureClustering, "lowinter")
d = plotFeatureClustering(uplingModel, uplingFilteredFeatures, uplingFeatureClustering, "upling")
e = plotFeatureClustering(upinterModel, upinterFilteredFeatures, upinterFeatureClustering, "upinter")
f = plotFeatureClustering(salivaModel, salivaFilteredFeatures, salivaFeatureClustering, "saliva")
ggarrange(a,b,c,d,e,f)
```

```{r corrected full feature plots}
correctedFeaturePlot = function(model){
  numComponents = ncol(model[[3]]) - 1
  Btilde = correctPARAFACloadings(model, 2)
  
  if(numComponents == 2){
    Btilde %>% as_tibble() %>% mutate(asv = model[[2]]$asv) %>% left_join(HOMD_mapping) %>% ggplot(aes(x=V1,y=V2,label=homd)) + geom_point() + geom_label_repel()
  }
  else{
    jitter = jitter(rep(0, nrow(model[[2]])))
    Btilde %>% as_tibble() %>% mutate(asv = model[[2]]$asv) %>% left_join(HOMD_mapping) %>% ggplot(aes(x=V1,y=jitter,label=homd)) + geom_point() + geom_label_repel()
  }
}

correctedFeaturePlot(tongueModel)
correctedFeaturePlot(lowlingModel)
correctedFeaturePlot(lowinterModel)
correctedFeaturePlot(uplingModel)
correctedFeaturePlot(upinterModel)
correctedFeaturePlot(salivaModel)
```

```{r experimental plot for mutual exclusivity}
testExclusivity = function(microbiome.raw, nicheName, featureClustering, minReads=0, presenceFrac=0.5){
  numGroups = max(featureClustering$group)
  numCombinations = 2**numGroups - numGroups - 1
  df = microbiome.raw %>% as_tibble() %>% filter(group == "control", niche == nicheName) %>% select(-sample, -group, -niche)
  df.numeric = df[,3:ncol(df)]
  
  results = list()
  for(i in 1:max(featureClustering$group)){
    dummy =  df.numeric %>% select(featureClustering %>% filter(group == i) %>% select(asv) %>% pull())
    dummy = dummy > minReads
    dummy = rowSums(dummy) / ncol(dummy)
    #dummy = apply(dummy, 1, mean)
    results[[i]] = dummy
  }
  
  presenceAbsence = as.data.frame(do.call(cbind, results))
  presenceAbsence = presenceAbsence > presenceFrac
  allResults = list()
  summaryPvalues = list()
  testResults = list()
  summaryIterator = 1
  for(i in 1:(numGroups-1)){
    for(j in (i+1):numGroups){
        #print(i)
        #print(j)
        result = matrix(c(sum(presenceAbsence[,i] & presenceAbsence[,j]), sum(!presenceAbsence[,i] & presenceAbsence[,j]), sum(presenceAbsence[,i] & !presenceAbsence[,j]), sum(!presenceAbsence[,i] & !presenceAbsence[,j])), nrow=2, ncol=2)
        #print(result)
        testResult = fisher.test(result, alternative="less")
        #print(testResult)
        #print("-------------------------------------------")
        allResults[[summaryIterator]] = result
        testResults[[summaryIterator]] = testResult
        summaryPvalues[summaryIterator] = testResult$p.value
        summaryIterator = summaryIterator + 1
    }
  }
  return(list(presenceAbsence,allResults, testResults, unlist(summaryPvalues)))

}

tongueExclusivity = testExclusivity(microbiome.raw, "tongue", tongueFeatureClustering)
lowlingExclusivity = testExclusivity(microbiome.raw, "lower jaw, lingual", lowlingFeatureClustering)
lowinterExclusivity = testExclusivity(microbiome.raw, "lower jaw, interproximal", lowinterFeatureClustering)
uplingExclusivity = testExclusivity(microbiome.raw, "upper jaw, lingual", uplingFeatureClustering)
upinterExclusivity = testExclusivity(microbiome.raw, "upper jaw, interproximal", upinterFeatureClustering)
salivaExclusivity = testExclusivity(microbiome.raw, "saliva", salivaFeatureClustering)
```

```{r small interjection}
plotMicrobiomeRelAb_timepoint = function(nicheName, featureClustering){
  microbiome.numeric = microbiome.raw %>% as_tibble() %>% filter(group=="control", niche==nicheName)
  microbiome.meta = microbiome.numeric %>% select(subject,visit)

  days = c(-14,0,2,5,9,14,21)
  RFgroupNames = c("Low responders", "Mid responders", "High responders")
  
  df = microbiome.numeric %>%
    select(all_of(c(featureClustering$asv, "subject", "visit"))) %>%
    pivot_longer(-c(subject,visit)) %>%
    left_join(featureClustering, by=c("name"="asv")) %>% 
    group_by(subject, visit, group) %>% 
    summarize(s = log10(sum(value)+1)) %>% 
    ungroup() %>%
    left_join(rf) %>% 
    mutate(RFgroup = as.factor(RFgroup)) %>%
    select(-subject) %>%
    group_by(RFgroup, visit, group) %>%
    summarize(m = mean(s, na.rm=TRUE), v = plotrix::std.error(s,na.rm=TRUE)) %>%
    ungroup() %>%
    mutate(RFgroup = as.numeric(RFgroup)) %>%
    mutate(visit = days[visit], RFgroup = RFgroupNames[RFgroup])
  
  df %>%
    ggplot(aes(x=visit,y=m,col=as.factor(group))) +
    facet_grid(~factor(RFgroup, levels=c("Low responders", "Mid responders", "High responders"))) +
    geom_line() +
    geom_point() + 
    geom_errorbar(aes(ymax=m+v,ymin=m-v), width=.2) +
    xlab("Day") +
    ylab("Mean sum of ASVs per group (mean +/- SEM)") +
    ggtitle(nicheName) +
    scale_colour_discrete(name = "ASV group")
}

plotMicrobiomeRelAb_timepoint("tongue", tongueFeatureClustering)
plotMicrobiomeRelAb_timepoint("lower jaw, lingual", lowlingFeatureClustering)
plotMicrobiomeRelAb_timepoint("lower jaw, interproximal", lowinterFeatureClustering)
plotMicrobiomeRelAb_timepoint("upper jaw, lingual", uplingFeatureClustering)
plotMicrobiomeRelAb_timepoint("upper jaw, interproximal", upinterFeatureClustering)
plotMicrobiomeRelAb_timepoint("saliva", salivaFeatureClustering)
```

```{r extra}
plotMicrobiomeRelAb_timepoint2 = function(nicheName, featureClustering){
  microbiome.numeric = microbiome.raw %>% as_tibble() %>% filter(group=="control", niche==nicheName)
  microbiome.meta = microbiome.numeric %>% select(subject,visit)
  microbiome.numeric = microbiome.numeric %>% select(-sample,-subject,-visit,-group,-niche)
  totalSums = rowSums(microbiome.numeric)
  relativeAbundances = sweep(microbiome.numeric, 1, totalSums, FUN="/") %>% as_tibble() %>% mutate(subject = microbiome.meta$subject, visit=microbiome.meta$visit)

  days = c(-14,0,2,5,9,14,21)
  RFgroupNames = c("Low responders", "Mid responders", "High responders")
  
  df = relativeAbundances %>%
    select(all_of(c(featureClustering$asv, "subject", "visit"))) %>%
    pivot_longer(-c(subject,visit)) %>%
    left_join(featureClustering, by=c("name"="asv")) %>% 
    group_by(subject, visit, group) %>% 
    summarize(s = sum(value)) %>% 
    ungroup() %>%
    left_join(rf) %>% 
    mutate(RFgroup = as.factor(RFgroup)) %>%
    select(-subject) %>%
    group_by(RFgroup, visit, group) %>%
    summarize(m = mean(s, na.rm=TRUE), v = plotrix::std.error(s,na.rm=TRUE)) %>%
    ungroup() %>%
    mutate(RFgroup = as.numeric(RFgroup)) %>%
    mutate(visit = days[visit], RFgroup = RFgroupNames[RFgroup])
  
  df %>%
    ggplot(aes(x=visit,y=m,col=as.factor(RFgroup))) +
    facet_grid(~factor(group)) +
    geom_line() +
    geom_point() + 
    geom_errorbar(aes(ymax=m+v,ymin=m-v), width=.2) +
    xlab("Day") +
    ylab("Relative abundance sum (mean +/- SEM)") +
    ggtitle(nicheName)
}

plotMicrobiomeRelAb_timepoint2("tongue", tongueFeatureClustering)
plotMicrobiomeRelAb_timepoint2("lower jaw, lingual", lowlingFeatureClustering)
plotMicrobiomeRelAb_timepoint2("lower jaw, interproximal", lowinterFeatureClustering)
plotMicrobiomeRelAb_timepoint2("upper jaw, lingual", uplingFeatureClustering)
plotMicrobiomeRelAb_timepoint2("upper jaw, interproximal", upinterFeatureClustering)
plotMicrobiomeRelAb_timepoint2("saliva", salivaFeatureClustering)
```

```{r attempt to put this into one figure}
microbiome.numeric = microbiome.raw %>% as_tibble() %>% filter(group=="control", niche != "lower jaw, interproximal")
microbiome.meta = microbiome.numeric %>% select(subject,visit, niche)
microbiome.numeric = microbiome.numeric %>% select(-sample,-subject,-visit,-group,-niche)
totalSums = rowSums(microbiome.numeric)
relativeAbundances = sweep(microbiome.numeric, 1, totalSums, FUN="/") %>% as_tibble() %>% mutate(subject = microbiome.meta$subject, visit=microbiome.meta$visit, niche=microbiome.meta$niche)

days = c(-14,0,2,5,9,14,21)
RFgroupNames = c("Low responders", "Mid responders", "High responders")
featureClustering = rbind(tongueFeatureClustering %>% mutate(niche="tongue") %>% select(niche,asv, group),
                          lowlingFeatureClustering %>% mutate(niche="lower jaw, lingual") %>% select(niche,asv, group),
                          uplingFeatureClustering %>% mutate(niche="upper jaw, lingual") %>% select(niche,asv, group),
                          upinterFeatureClustering %>% mutate(niche="upper jaw, interproximal") %>% filter(group %in% c(1,2)) %>% select(niche,asv, group),
                          salivaFeatureClustering %>% mutate(niche="saliva") %>% select(niche,asv, group))

df = relativeAbundances %>%
  select(all_of(c(featureClustering$asv, "subject", "visit", "niche"))) %>%
  pivot_longer(-c(subject,visit,niche)) %>%
  left_join(featureClustering, by=c("name"="asv","niche")) %>% 
  filter(group != "NA") %>%
  group_by(niche, subject, visit, group) %>% 
  summarize(s = log10(sum(value)+1)) %>% 
  ungroup() %>%
  left_join(rf) %>% 
  mutate(RFgroup = as.factor(RFgroup)) %>%
  select(-subject) %>%
  group_by(niche, RFgroup, visit, group) %>%
  summarize(m = mean(s, na.rm=TRUE), v = plotrix::std.error(s,na.rm=TRUE)) %>%
  ungroup() %>%
  mutate(RFgroup = as.numeric(RFgroup)) %>%
  mutate(visit = days[visit], RFgroup = RFgroupNames[RFgroup])

df %>%
  ggplot(aes(x=visit,y=m,col=as.factor(RFgroup))) +
  facet_grid(vars(niche),vars(group)) +
  geom_line() +
  geom_point() + 
  geom_errorbar(aes(ymax=m+v,ymin=m-v), width=.2) +
  xlab("Day") +
  ylab("Relative abundance sum (mean +/- SEM)") +
  scale_color_discrete(name="Response group")
```

```{r test hypotheses}
testHypothesis = function(nicheName, visitNumber, featureClustering, groupNumber){
  microbiome.numeric = microbiome.raw %>% as_tibble() %>% filter(group=="control", niche==nicheName)
  
  df = microbiome.numeric %>%
    filter(visit==visitNumber) %>%
    select(all_of(c(featureClustering$asv,"subject"))) %>% 
    pivot_longer(-subject) %>% 
    left_join(featureClustering, by=c("name"="asv")) %>%
    left_join(rf) %>%
    filter(group == groupNumber) %>%
    group_by(RFgroup, group, subject) %>% 
    summarize(s = sum(value)+1) %>%
    ungroup()
  
  df %>%
    ggplot(aes(x=as.factor(RFgroup),y=s,fill=as.factor(RFgroup))) +
    geom_boxplot() + 
    stat_compare_means(method="wilcox.test", comparisons=list(c(1,2),c(2,3),c(1,3))) +
    scale_y_log10() +
    xlab("Responder group") +
    ylab("Sum of ASVs in group") +
    ggtitle(paste0(nicheName, " (group ", groupNumber, ")"))
}

# Visit 1
testHypothesis("tongue", 1, tongueFeatureClustering, 1)
testHypothesis("tongue", 1, tongueFeatureClustering, 2)
testHypothesis("lower jaw, lingual", 1, lowlingFeatureClustering, 1)
testHypothesis("lower jaw, lingual", 1, lowlingFeatureClustering, 2)
testHypothesis("lower jaw, interproximal", 1, lowinterFeatureClustering, 1)
testHypothesis("lower jaw, interproximal", 1, lowinterFeatureClustering, 2)
testHypothesis("upper jaw, lingual", 1, uplingFeatureClustering, 1)
testHypothesis("upper jaw, lingual", 1, uplingFeatureClustering, 2)
testHypothesis("upper jaw, interproximal", 1, upinterFeatureClustering, 1)
testHypothesis("upper jaw, interproximal", 1, upinterFeatureClustering, 2)
testHypothesis("upper jaw, interproximal", 1, upinterFeatureClustering, 3)
testHypothesis("upper jaw, interproximal", 1, upinterFeatureClustering, 4)
testHypothesis("saliva", 1, salivaFeatureClustering, 1)
testHypothesis("saliva", 1, salivaFeatureClustering, 2)
```

```{r test in a different way - permutations}
ASVgroupPermutationTest = function(nicheName, featureClustering, visitNumber, groupNumber, numPermutations){
  microbiome.numeric = microbiome.raw %>% as_tibble() %>% filter(group=="control", niche==nicheName, visit==visitNumber)
  microbiome.meta = microbiome.numeric %>% select(subject)
  microbiome.numeric = microbiome.numeric %>% select(-sample,-subject,-visit,-group,-niche)
  totalSums = rowSums(microbiome.numeric)
  relativeAbundances = sweep(microbiome.numeric, 1, totalSums, FUN="/") %>% as_tibble() %>% mutate(subject = microbiome.meta$subject)

  df = relativeAbundances %>%
    select(all_of(c(featureClustering$asv, "subject"))) %>%
    pivot_longer(-subject) %>%
    left_join(featureClustering, by=c("name"="asv")) %>%
    group_by(subject, group) %>%
    summarize(s=sum(value), .groups="drop") %>%
    ungroup() %>%
    left_join(rf, by="subject") %>%
    filter(group == groupNumber)
  
  dfA = df %>% filter(RFgroup==0) %>% select(s) %>% pull()
  dfB = df %>% filter(RFgroup==2) %>% select(s) %>% pull()
  #realResult = wilcox.test(dfA, dfB)$p.value
  realResult = mean(dfA) - mean(dfB)
  
  # Permutations
  set.seed(1)
  permutedResults = 1:numPermutations
  for(i in 1:numPermutations){
    dfA = df %>% mutate(RFgroup = sample(RFgroup)) %>% filter(RFgroup==0) %>% select(s) %>% pull()
    dfB = df %>% mutate(RFgroup = sample(RFgroup)) %>% filter(RFgroup==2) %>% select(s) %>% pull()
    #permutedResults[i] = wilcox.test(dfA, dfB)$p.value
    permutedResults[i] = mean(dfA) - mean(dfB)
  }
  
  Zscore = abs(realResult - mean(permutedResults)) / sd(permutedResults)
  
  if (realResult < 0){
    pvalue = sum(permutedResults < realResult) / numPermutations
  }
  else{
    pvalue = sum(permutedResults > realResult) / numPermutations
  }
  
  return(list(realResult, permutedResults, mean(permutedResults), median(permutedResults), sd(permutedResults), Zscore, pvalue))
}

allResults = matrix(nrow=14, ncol=9)
iter=1
niches = c("tongue", "lower jaw, lingual", "lower jaw, interproximal", "upper jaw, lingual", "upper jaw, interproximal", "saliva")
featureClusterings = list(tongueFeatureClustering, lowlingFeatureClustering, lowinterFeatureClustering, uplingFeatureClustering, upinterFeatureClustering, salivaFeatureClustering)

for(i in 1:length(niches)){
  nicheName = niches[i]
  featureClustering = featureClusterings[[i]]
  numGroups = max(featureClustering$group)
  for(j in 1:numGroups){
    for(k in 1:7){
      permutationTestResult = ASVgroupPermutationTest(nicheName, featureClustering, k, j, 999)
      pvalue = permutationTestResult[[7]]
      
      if(k==1){
        allResults[iter, 1] = nicheName
        allResults[iter, 2] = j
      }
      allResults[iter, k+2] = pvalue
    }
    iter = iter + 1
  }
}

```

```{r proof of signal in ratio of groups}
testHypothesisRatio = function(nicheName, visitNumber, featureClustering, groupNumberA, groupNumberB){
  microbiome.numeric = microbiome.raw %>% as_tibble() %>% filter(group=="control", niche==nicheName)
  
  df = microbiome.numeric %>%
    filter(visit==visitNumber) %>%
    select(all_of(c(featureClustering$asv,"subject"))) %>% 
    pivot_longer(-subject) %>% 
    left_join(featureClustering, by=c("name"="asv")) %>%
    left_join(rf) %>%
    filter(group %in% c(groupNumberA, groupNumberB)) %>%
    group_by(RFgroup, group, subject) %>% 
    summarize(s = sum(value)+1) %>%
    ungroup() %>%
    pivot_wider(names_from="group", values_from=s)
  
  colnames(df) = c("RFgroup", "subject", "sumGroupA", "sumGroupB")
  
  df = df %>%
    mutate(ratio=sumGroupA/sumGroupB) %>%
    select(RFgroup, ratio)
  
  df %>%
    ggplot(aes(x=as.factor(RFgroup),y=ratio,fill=as.factor(RFgroup))) +
    geom_boxplot() + 
    stat_compare_means(comparisons=list(c(1,2),c(2,3),c(1,3))) +
    scale_y_log10() +
    xlab("Responder group") +
    ylab("Sum of ASVs in group") +
    ggtitle(paste0(nicheName, " (group ", groupNumberA, " vs. group ", groupNumberB, ")"))
}

# Visit 1
testHypothesisRatio("tongue", 1, tongueFeatureClustering, 1, 2)
testHypothesisRatio("lower jaw, lingual", 1, lowlingFeatureClustering, 1, 2)
testHypothesisRatio("lower jaw, interproximal", 1, lowinterFeatureClustering, 1, 2)
testHypothesisRatio("upper jaw, lingual", 1, uplingFeatureClustering, 1, 2)
testHypothesisRatio("upper jaw, interproximal", 1, upinterFeatureClustering, 1, 2)
testHypothesisRatio("upper jaw, interproximal", 1, upinterFeatureClustering, 1, 3)
testHypothesisRatio("upper jaw, interproximal", 1, upinterFeatureClustering, 1, 4)
testHypothesisRatio("upper jaw, interproximal", 1, upinterFeatureClustering, 2, 3)
testHypothesisRatio("upper jaw, interproximal", 1, upinterFeatureClustering, 2, 4)
testHypothesisRatio("upper jaw, interproximal", 1, upinterFeatureClustering, 3, 4)
testHypothesisRatio("saliva", 1, salivaFeatureClustering, 1, 2)

# Visit 2
testHypothesisRatio("tongue", 2, tongueFeatureClustering, 1, 2)
testHypothesisRatio("lower jaw, lingual", 2, lowlingFeatureClustering, 1, 2)
testHypothesisRatio("lower jaw, interproximal", 2, lowinterFeatureClustering, 1, 2)
testHypothesisRatio("upper jaw, lingual", 2, uplingFeatureClustering, 1, 2)
testHypothesisRatio("upper jaw, interproximal", 2, upinterFeatureClustering, 1, 2)
testHypothesisRatio("upper jaw, interproximal", 2, upinterFeatureClustering, 1, 3)
testHypothesisRatio("upper jaw, interproximal", 2, upinterFeatureClustering, 1, 4)
testHypothesisRatio("upper jaw, interproximal", 2, upinterFeatureClustering, 2, 3)
testHypothesisRatio("upper jaw, interproximal", 2, upinterFeatureClustering, 2, 4)
testHypothesisRatio("upper jaw, interproximal", 2, upinterFeatureClustering, 3, 4)
testHypothesisRatio("saliva", 2, salivaFeatureClustering, 1, 2)
```

```{r check correlations with R14}
testSumCorrelation = function(nicheName, visitNumber, featureClustering, groupNumber){
  microbiome.numeric = microbiome.raw %>% as_tibble() %>% filter(group=="control", niche==nicheName)
  
  df = microbiome.numeric %>%
    filter(visit==visitNumber) %>%
    select(all_of(c(featureClustering$asv,"subject"))) %>% 
    pivot_longer(-subject) %>% 
    left_join(featureClustering, by=c("name"="asv")) %>%
    left_join(rf) %>%
    filter(group == groupNumber) %>%
    group_by(RFgroup, group, subject) %>% 
    summarize(s = sum(value)) %>%
    ungroup() %>%
    left_join(rf_data %>% filter(day==14) %>% select(subject, bomppercent))
  
  testResult = cor.test(df$s, df$bomppercent)
  
  df %>% ggplot(aes(x=s,y=bomppercent)) + geom_point() + ggtitle(paste0(nicheName, " group ", groupNumber, " (p=", testResult$p.value, ")"))
}

testSumCorrelation("tongue", 1, tongueFeatureClustering, 1)
testSumCorrelation("tongue", 1, tongueFeatureClustering, 2)
testSumCorrelation("lower jaw, lingual", 1, lowlingFeatureClustering, 1)
testSumCorrelation("lower jaw, lingual", 1, lowlingFeatureClustering, 2)
testSumCorrelation("lower jaw, interproximal", 1, lowinterFeatureClustering, 1)
testSumCorrelation("lower jaw, interproximal", 1, lowinterFeatureClustering, 2)
testSumCorrelation("upper jaw, lingual", 1, uplingFeatureClustering, 1)
testSumCorrelation("upper jaw, lingual", 1, uplingFeatureClustering, 2)
testSumCorrelation("upper jaw, interproximal", 1, upinterFeatureClustering, 1)
testSumCorrelation("upper jaw, interproximal", 1, upinterFeatureClustering, 2)
testSumCorrelation("upper jaw, interproximal", 1, upinterFeatureClustering, 3)
testSumCorrelation("upper jaw, interproximal", 1, upinterFeatureClustering, 4)
testSumCorrelation("saliva", 1, salivaFeatureClustering, 1)
testSumCorrelation("saliva", 1, salivaFeatureClustering, 2)
```

```{r sqeeze statistics}
microbiome.numeric = microbiome.raw %>% as_tibble() %>% filter(group=="control")
featureClustering = rbind(tongueFeatureClustering %>% mutate(niche="tongue") %>% select(niche,asv, group),
                          lowlingFeatureClustering %>% mutate(niche="lower jaw, lingual") %>% select(niche,asv, group),
                          lowinterFeatureClustering %>% mutate(niche="lower jaw, interproximal") %>% select(niche,asv, group),
                          uplingFeatureClustering %>% mutate(niche="upper jaw, lingual") %>% select(niche,asv, group),
                          upinterFeatureClustering %>% mutate(niche="upper jaw, interproximal") %>% select(niche,asv, group),
                          salivaFeatureClustering %>% mutate(niche="saliva") %>% select(niche,asv, group))

df = microbiome.numeric %>% filter(visit==1) %>% select(-sample,-visit,-group) %>% pivot_longer(-c(subject,niche)) %>% mutate(asv=name) %>% select(-name) %>% left_join(featureClustering) %>% filter(group != "NA") %>% group_by(subject,niche,group) %>% summarize(s=sum(value,na.rm=TRUE)) %>% left_join(rf) %>% mutate(colname = paste0(make.names(niche),group)) %>% ungroup() %>% select(-niche,-group) %>% pivot_wider(names_from=colname,values_from=s)

df = df[!apply(df, 1, function(x){any(is.na(x))}),]
df = df %>% select(-subject)
```

```{r as a heatmap}
hclust.ward = function(x) hclust(x, method="ward.D")
dist.pear = function(x) as.dist(1-cor(t(x)))

plotMicrobiomeRelAb_heatmap = function(model, featureClustering, subjectClustering){
  
  for(i in 1:nrow(model[[3]])){
      day = model[[3]]$days[i]
      
      inputData = model[[7]] %>%
      mutate(timepoint = rep(model[[3]]$days, nrow(model[[1]])), subject = rep(model[[1]]$subject, each=nrow(model[[3]]))) %>%
      filter(timepoint==day) %>% 
      select(-timepoint) %>%
      pivot_longer(-subject) %>%
      mutate(asv=name) %>%
      select(-name) %>%
      left_join(featureClustering) %>%
      filter(group != "NA") %>%
      select(subject, asv, group, value) %>%
      pivot_wider(names_from=subject, values_from=value) %>%
      arrange(group)
    
      ASVgroup = inputData$group
      ASVnames = inputData %>% left_join(model[[2]]) %>% mutate(name = paste0(Genus, " ", Species)) %>% select(name) %>% pull()
      colnames(inputData) = make.names(colnames(inputData))
      subjectGroup = subjectClustering %>% arrange(group) %>% select(group) %>% pull()
      
      subjectOrdering = make.names(subjectClustering %>% arrange(group) %>% select(subject) %>% pull())
      inputData = inputData %>% select(all_of(subjectOrdering)) %>% as.matrix()
      row.names(inputData) = ASVnames
        
      P50 = createPalette(50,  c("#ff0000", "#00ff00", "#0000ff")) # red=0, green=1, blue=2
      rowCols = P50[ASVgroup]
      colCols = P50[subjectGroup]
      heatmap.2a(inputData, Rowv=NA, Colv=NA, scale="none", col=heat.colors(256), trace="none", dendrogram="none", RowSideColors=rowCols, ColSideColors=colCols, density.info="histogram")
  }

}

plotMicrobiomeRelAb_heatmap(tongueModel, tongueFeatureClustering, tongueSubjectClustering)
plotMicrobiomeRelAb_heatmap(lowlingModel, lowlingFeatureClustering, lowlingSubjectClustering)
plotMicrobiomeRelAb_heatmap(lowinterModel, lowinterFeatureClustering, lowinterSubjectClustering)
plotMicrobiomeRelAb_heatmap(uplingModel, uplingFeatureClustering, uplingSubjectClustering)
plotMicrobiomeRelAb_heatmap(upinterModel, upinterFeatureClustering, upinterSubjectClustering)
plotMicrobiomeRelAb_heatmap(salivaModel, salivaFeatureClustering, salivaSubjectClustering)
```

```{r presence absence heatmap}

microbiome.numeric = microbiome.raw %>% as_tibble() %>% filter(group=="control", niche=="lower jaw, lingual")
microbiome.meta = microbiome.numeric %>% select(subject,visit)
presenceAbsence = microbiome.numeric %>% select(-sample,-subject,-visit,-niche,-group)
presenceAbsence = presenceAbsence > 0
presenceAbsence = 1*presenceAbsence
presenceAbsence = presenceAbsence %>% as_tibble() %>% mutate(subject = microbiome.meta$subject, visit = microbiome.meta$visit)

df = presenceAbsence %>% filter(visit==1) %>% left_join(lowlingSubjectClustering) %>% arrange(group, subject) 
subjectNames = df$subject
df = df %>% select(lowlingFeatureClustering %>% arrange(group) %>% select(asv) %>% pull()) %>% t()
colnames(df) = make.names(subjectNames)
#colnames(df) = lowlingSubjectClustering %>% arrange(group) %>% select(subject) %>% pull()
df = as.matrix(df)
my_palette <- colorRampPalette(c("red", "blue"))(n = 50)
#heatmap.2a(df, trace="none", Rowv=NA, Colv=NA, dendrogram="none")

P50 = createPalette(50,  c("#ff0000", "#00ff00", "#0000ff")) # red=0, green=1, blue=2
ASVgroup = row.names(df) %>% as_tibble() %>% mutate(asv = value) %>% left_join(lowlingFeatureClustering) %>% select(group) %>% pull()
subjectGroup = presenceAbsence %>% filter(visit==1) %>% left_join(lowlingSubjectClustering) %>% arrange(group, subject) %>% select(group) %>% pull()
rowCols = P50[ASVgroup]
colCols = P50[subjectGroup]
row.names(df) = row.names(df) %>% as_tibble() %>% mutate(asv=value) %>% left_join(taxa) %>% mutate(newName = paste0(Genus," ", Species)) %>% select(newName) %>% pull()      
heatmap.2a(df, trace="none", Rowv=NA, Colv=NA, dendrogram="none", col=my_palette, colsep=1:ncol(df), rowsep=1:nrow(df), sepcolor="black", sepwidth=c(0.1,0.1), RowSideColors=rowCols, ColSideColors=colCols, cexRow=2, cexCol=2)
```

```{r presence absence heatmap summarized}
microbiome.numeric = microbiome.raw %>% as_tibble() %>% filter(group=="control", niche=="lower jaw, lingual")
microbiome.meta = microbiome.numeric %>% select(subject,visit)
presenceAbsence = microbiome.numeric %>% select(-sample,-subject,-visit,-niche,-group)
presenceAbsence = presenceAbsence > 0
presenceAbsence = 1*presenceAbsence
presenceAbsence = presenceAbsence %>% as_tibble() %>% mutate(subject = microbiome.meta$subject, visit = microbiome.meta$visit)

df = presenceAbsence %>% filter(visit==1) %>% left_join(lowlingSubjectClustering) %>% arrange(group, subject)
subjectNames = df$subject
df = df %>% select(lowlingFeatureClustering %>% arrange(group) %>% select(asv) %>% pull()) %>% t()

rowA = 1*((df[1:(nrow(df)-1),] %>% colSums() / (nrow(df)-1)) > 0.5)
rowB = df[nrow(df),]
temp = rbind(rowA, rowB)
temp = temp %>% as_tibble() %>% mutate(group=1:2) 
colnames(temp) = c(make.names(subjectNames), "group")

my_palette <- colorRampPalette(c("red", "blue"))(n = 50)
temp = temp %>% select(-group) %>% as.matrix()

P50 = createPalette(50,  c("#ff0000", "#00ff00", "#0000ff")) # red=0, green=1, blue=2
#ASVgroup = row.names(temp) %>% as_tibble() %>% mutate(asv = value) %>% left_join(lowlingFeatureClustering) %>% select(group) %>% pull()
subjectGroup = subjectNames %>% as_tibble() %>% mutate(subject=value) %>% left_join(lowlingSubjectClustering) %>% select(group) %>% pull()
#rowCols = P50[ASVgroup]
colCols = P50[subjectGroup]

heatmap.2a(temp, trace="none", Rowv=NA, Colv=NA, dendrogram="none", col=my_palette, colsep=1:ncol(temp), rowsep=1:nrow(temp), sepcolor="black", sepwidth=c(0.1,0.1), ColSideColors=colCols)
```

```{r KNN clustering of the subjects}
clusterSubjectLoadings_filtered = function(model, filteredSubjects, numClusters){
  numComponents = ncol(model[[3]]) - 1
  Atilde = correctPARAFACloadings(model, 1)
  colnames(Atilde) = paste0("Component_", 1:numComponents)
  df = Atilde %>% as_tibble() %>% mutate(subject=model[[1]]$subject) %>% left_join(filteredSubjects) %>% filter(keep==1)
  result = df
  
  if(numComponents==1){
    df = df %>% select(Component_1) %>% as.matrix()
  }
  else{
    df = df %>% select(Component_1, Component_2) %>% as.matrix()
  }
  
  result$group = kmeans(df, numClusters, nstart=50)$cluster
  
  return(result)
}

tongueFilteredSubjects = tongueModel[[1]] %>% mutate(keep = 1) %>% select(subject, keep)
tongueSubjectClustering = clusterSubjectLoadings_filtered(tongueModel, tongueFilteredSubjects, 3)
a = plotSubjectClustering(tongueModel, tongueSubjectClustering, "tongue")
b = plotSubjectClustering_meta(tongueModel, tongueSubjectClustering, "tongue")
ggarrange(a,b)

lowlingFilteredSubjects = lowlingModel[[1]] %>% mutate(keep = 1) %>% select(subject, keep)
lowlingSubjectClustering = clusterSubjectLoadings_filtered(lowlingModel, lowlingFilteredSubjects, 2)
a = plotSubjectClustering(lowlingModel, lowlingSubjectClustering, "lowling")
b = plotSubjectClustering_meta(lowlingModel, lowlingSubjectClustering, "lowling")
ggarrange(a,b)

lowinterFilteredSubjects = lowinterModel[[1]] %>% mutate(keep = 1) %>% select(subject, keep)
lowinterSubjectClustering = clusterSubjectLoadings_filtered(lowinterModel, lowinterFilteredSubjects, 2)
a = plotSubjectClustering(lowinterModel, lowinterSubjectClustering, "lowinter")
b = plotSubjectClustering_meta(lowinterModel, lowinterSubjectClustering, "lowinter")
ggarrange(a,b)

uplingFilteredSubjects = uplingModel[[1]] %>% mutate(keep = 1) %>% select(subject, keep)
uplingSubjectClustering = clusterSubjectLoadings_filtered(uplingModel, uplingFilteredSubjects, 2)
a = plotSubjectClustering(uplingModel, uplingSubjectClustering, "upling")
b = plotSubjectClustering_meta(uplingModel, uplingSubjectClustering, "upling")
ggarrange(a,b)

upinterFilteredSubjects = upinterModel[[1]] %>% mutate(keep = 1) %>% select(subject, keep)
upinterSubjectClustering = clusterSubjectLoadings_filtered(upinterModel, upinterFilteredSubjects, 2)
a = plotSubjectClustering(upinterModel, upinterSubjectClustering, "upinter")
b = plotSubjectClustering_meta(upinterModel, upinterSubjectClustering, "upinter")
ggarrange(a,b)

salivaFilteredSubjects = salivaModel[[1]] %>% mutate(keep = 1) %>% select(subject, keep)
salivaSubjectClustering = clusterSubjectLoadings_filtered(salivaModel, salivaFilteredSubjects, 3)
a = plotSubjectClustering(salivaModel, salivaSubjectClustering, "saliva")
b = plotSubjectClustering_meta(salivaModel, salivaSubjectClustering, "saliva")
ggarrange(a,b)

metabolomicsFilteredSubjects = metabolomicsModel[[1]] %>% mutate(keep = 1) %>% select(subject, keep)
metabolomicsSubjectClustering = clusterSubjectLoadings_filtered(metabolomicsModel, metabolomicsFilteredSubjects, 2)
a = plotSubjectClustering(metabolomicsModel, metabolomicsSubjectClustering, "metabolomics")
b = plotSubjectClustering_meta(metabolomicsModel, metabolomicsSubjectClustering, "metabolomics")
ggarrange(a,b)
```

```{r figure for paper}
plotSubjectClustering = function(model, subjectClustering, title){
  numComponents = ncol(model[[3]]) - 1
  
  if(numComponents==1){
    plot = subjectClustering %>% ggplot(aes(x=Component_1,y=0,col=as.factor(group))) + geom_point() + geom_vline(xintercept=0, linetype=2) + ggtitle(title)
  }
  else{
    plot = subjectClustering %>% ggplot(aes(x=Component_1,y=Component_2,col=as.factor(group))) + geom_point() + geom_vline(xintercept=0, linetype=2) + geom_hline(yintercept=0, linetype=2) + ggtitle(title)
  }
  
  return(plot)
}

a = plotSubjectClustering(tongueModel, tongueSubjectClustering, "tongue")
b = plotSubjectClustering(lowlingModel, lowlingSubjectClustering, "lowling")
c = plotSubjectClustering(lowinterModel, lowinterSubjectClustering, "lowinter")
d = plotSubjectClustering(uplingModel, uplingSubjectClustering, "upling")
e = plotSubjectClustering(upinterModel, upinterSubjectClustering, "upinter")
f = plotSubjectClustering(salivaModel, salivaSubjectClustering, "saliva")
ggarrange(a,b,c,d,e,f, nrow=2, ncol=3)
```
## Inspecting the outcome in the input and original data

```{r check names of asvs in each group}
reportNamesPerGroup = function(featureClustering){
  numClusters = max(featureClustering$group)
  
  for(i in 1:numClusters){
    print(i)
    df = featureClustering %>% filter(group == i) %>% select(asv, Genus, Species, homd)
    print(df)
  }
}

reportNamesPerGroup(tongueFeatureClustering)
reportNamesPerGroup(lowlingFeatureClustering)
reportNamesPerGroup(lowinterFeatureClustering)
reportNamesPerGroup(uplingFeatureClustering)
reportNamesPerGroup(upinterFeatureClustering)
reportNamesPerGroup(salivaFeatureClustering)

featureClustering = metabolomicsFeatureClustering
for(i in 1:numClusters){
  print(i)
  df = featureClustering %>% filter(group == i) %>% select(BIOCHEMICAL, SUB_PATHWAY, SUPER_PATHWAY)
  print(df)
}
```

```{r meta plot}
metaPlot = function(model, featureClustering, subjectClustering){
  plotList = list()
  numFeatureGroups = max(featureClustering$group)
  numSubjectGroups = max(subjectClustering$group)
  numComponents = ncol(model[[3]]) - 1
  
  plotIndex = 1
  for(i in 1:numSubjectGroups){
    plotList[[plotIndex]] = plotResponsePerSubjectGroup(model, featureClustering, subjectClustering, i)
    plotIndex = plotIndex + 1
  }
  for(j in 1:numFeatureGroups){
    plotList[[plotIndex]] = plotResponsePerFeatureGroup(model, featureClustering, subjectClustering, j)
    plotIndex = plotIndex + 1
  }

  plotList[[plotIndex]] = plotFeatureClustering(model, featureClustering, "Feature loadings")
  plotIndex = plotIndex + 1
  plotList[[plotIndex]] = plotFeatureClustering_meta(model, featureClustering, "Feature loadings")
  plotIndex = plotIndex + 1
  plotList[[plotIndex]] = plotSubjectClustering(model, subjectClustering, "Subject loadings")
  plotIndex = plotIndex + 1
  plotList[[plotIndex]] = plotSubjectClustering_meta(model, subjectClustering, "Subject loadings")
  
  ggarrange(plotlist=plotList)
}

metaPlot(tongueModel, tongueFeatureClustering, tongueSubjectClustering)
metaPlot(lowlingModel, lowlingFeatureClustering, lowlingSubjectClustering)
metaPlot(lowinterModel, lowinterFeatureClustering, lowinterSubjectClustering)
metaPlot(uplingModel, uplingFeatureClustering, uplingSubjectClustering)
metaPlot(upinterModel, upinterFeatureClustering, upinterSubjectClustering)
metaPlot(salivaModel, salivaFeatureClustering, salivaSubjectClustering)

model = metabolomicsModel
featureClustering = metabolomicsFeatureClustering
subjectClustering = metabolomicsSubjectClustering
featureClusteringResult = metabolomicsFeatureClustering
subjectClusteringResult = metabolomicsSubjectClustering

plotList = list()
numFeatureGroups = max(featureClustering$group)
numSubjectGroups = max(subjectClustering$group)
numComponents = ncol(model[[3]]) - 1

plotIndex = 1
for(i in 1:numSubjectGroups){
    df = model[[7]] %>% mutate(timepoint = rep(model[[3]]$days, nrow(model[[1]])), subject = rep(model[[1]]$subject, each=nrow(model[[3]]))) %>% pivot_longer(-c(timepoint,subject))
    plotSubjects = subjectClusteringResult %>% filter(group == i) %>% select(subject) %>% pull
    plot = df %>% left_join(featureClusteringResult, by=c("name" = "BIOCHEMICAL")) %>% filter(subject %in% plotSubjects, group %in% 1:numFeatureGroups) %>% ggplot(aes(x=as.factor(timepoint),y=value,fill=as.factor(group))) + geom_boxplot() + geom_hline(yintercept=0, linetype=3) + ggtitle(paste0("Subject group ", i))
    
    plotList[[plotIndex]] = plot
    plotIndex = plotIndex + 1
}

for(j in 1:numFeatureGroups){
    df = model[[7]] %>% mutate(timepoint = rep(model[[3]]$days, nrow(model[[1]])), subject = rep(model[[1]]$subject, each=nrow(model[[3]]))) %>% pivot_longer(-c(timepoint,subject))
    plotFeatures = featureClusteringResult %>% filter(group == j) %>% select(BIOCHEMICAL) %>% pull
    plot = df %>% left_join(subjectClusteringResult) %>% filter(name %in% plotFeatures, group %in% 1:numSubjectGroups) %>% ggplot(aes(x=as.factor(timepoint),y=value,fill=as.factor(group))) + geom_boxplot() + geom_hline(yintercept=0, linetype=3) + ggtitle(paste0("Feature group ", j))
    
    plotList[[plotIndex]] = plot
    plotIndex = plotIndex + 1
}

plotList[[plotIndex]] = plotFeatureClustering(model, featureClustering, "Feature loadings")
plotIndex = plotIndex + 1
plotList[[plotIndex]] = featureClustering %>% ggplot(aes(x=Component_1,y=Component_2,col=as.factor(SUPER_PATHWAY))) + geom_point() + geom_vline(xintercept=0, linetype=2) + geom_hline(yintercept=0, linetype=2) + ggtitle(title)
plotIndex = plotIndex + 1
plotList[[plotIndex]] = plotSubjectClustering(model, subjectClustering, "Subject loadings")
plotIndex = plotIndex + 1
plotList[[plotIndex]] = plotSubjectClustering_meta(metabolomicsModel, metabolomicsSubjectClustering, "Subject loadings")

ggarrange(plotlist=plotList)
```

```{r more summaritive plot}
summarisingPlot = function(model, featureClustering, subjectClustering, title){
  df = model[[7]] %>%
    mutate(timepoint = rep(model[[3]]$days, nrow(model[[1]])), subject = rep(model[[1]]$subject, each=nrow(model[[3]]))) %>%
    pivot_longer(-c(timepoint,subject)) %>% 
    mutate(asv = name) %>% 
    select(-name) %>% 
    left_join(featureClustering) %>%
    mutate(featureGroup = group) %>% 
    select(timepoint, subject, value, asv, featureGroup) %>% 
    left_join(subjectClustering) %>%
    mutate(subjectGroup = group) %>%
    select(timepoint, subject, value, asv, featureGroup, subjectGroup) %>%
    filter(featureGroup != "NA") %>% 
    mutate(featureGroup = as.factor(featureGroup), subjectGroup = as.factor(subjectGroup))
  
  df %>% 
    ggplot(aes(x=featureGroup,y=value,fill=subjectGroup)) + 
    geom_boxplot() + 
    stat_compare_means(aes(group = subjectGroup), method="wilcox.test", label="p.signif") +
    xlab("Feature group") + 
    ylab("Value") + 
    ggtitle(title)
}

a = summarisingPlot(tongueModel, tongueFeatureClustering, tongueSubjectClustering, "Tongue")
b = summarisingPlot(lowlingModel, lowlingFeatureClustering, lowlingSubjectClustering, "Lower jaw, lingual")
c = summarisingPlot(lowinterModel, lowinterFeatureClustering, lowinterSubjectClustering, "Lower jaw, interproximal")
d = summarisingPlot(uplingModel, uplingFeatureClustering, uplingSubjectClustering, "Upper jaw, lingual")
e = summarisingPlot(upinterModel, upinterFeatureClustering, upinterSubjectClustering, "Upper jaw, interproximal")
f = summarisingPlot(salivaModel, salivaFeatureClustering, salivaSubjectClustering, "Saliva")
ggarrange(a,b,c,d,e,f, common.legend=TRUE)
```

```{r for table checking metadata - gender}
t.test(tongueModel[[1]] %>% left_join(age_gender) %>% filter(gender==1) %>% select(Component_1) %>% pull(), tongueModel[[1]] %>% left_join(age_gender) %>% filter(gender==2) %>% select(Component_1) %>% pull())
t.test(tongueModel[[1]] %>% left_join(age_gender) %>% filter(gender==1) %>% select(Component_2) %>% pull(), tongueModel[[1]] %>% left_join(age_gender) %>% filter(gender==2) %>% select(Component_2) %>% pull())

t.test(lowlingModel[[1]] %>% left_join(age_gender) %>% filter(gender==1) %>% select(Component_1) %>% pull(), lowlingModel[[1]] %>% left_join(age_gender) %>% filter(gender==2) %>% select(Component_1) %>% pull())

t.test(lowinterModel[[1]] %>% left_join(age_gender) %>% filter(gender==1) %>% select(Component_1) %>% pull(), lowinterModel[[1]] %>% left_join(age_gender) %>% filter(gender==2) %>% select(Component_1) %>% pull())

t.test(uplingModel[[1]] %>% left_join(age_gender) %>% filter(gender==1) %>% select(Component_1) %>% pull(), uplingModel[[1]] %>% left_join(age_gender) %>% filter(gender==2) %>% select(Component_1) %>% pull())
t.test(uplingModel[[1]] %>% left_join(age_gender) %>% filter(gender==1) %>% select(Component_2) %>% pull(), uplingModel[[1]] %>% left_join(age_gender) %>% filter(gender==2) %>% select(Component_2) %>% pull())

t.test(upinterModel[[1]] %>% left_join(age_gender) %>% filter(gender==1) %>% select(Component_1) %>% pull(), upinterModel[[1]] %>% left_join(age_gender) %>% filter(gender==2) %>% select(Component_1) %>% pull())
t.test(upinterModel[[1]] %>% left_join(age_gender) %>% filter(gender==1) %>% select(Component_2) %>% pull(), upinterModel[[1]] %>% left_join(age_gender) %>% filter(gender==2) %>% select(Component_2) %>% pull())

t.test(salivaModel[[1]] %>% left_join(age_gender) %>% filter(gender==1) %>% select(Component_1) %>% pull(), salivaModel[[1]] %>% left_join(age_gender) %>% filter(gender==2) %>% select(Component_1) %>% pull())
t.test(salivaModel[[1]] %>% left_join(age_gender) %>% filter(gender==1) %>% select(Component_2) %>% pull(), salivaModel[[1]] %>% left_join(age_gender) %>% filter(gender==2) %>% select(Component_2) %>% pull())
```

```{r for table checking metadata - age}
cor.test(tongueModel[[1]] %>% left_join(age_gender) %>% select(age) %>% pull(), tongueModel[[1]] %>% left_join(age_gender) %>% select(Component_1) %>% pull(), method="pearson")
cor.test(tongueModel[[1]] %>% left_join(age_gender) %>% select(age) %>% pull(), tongueModel[[1]] %>% left_join(age_gender) %>% select(Component_2) %>% pull(), method="pearson")

cor.test(lowlingModel[[1]] %>% left_join(age_gender) %>% select(age) %>% pull(), lowlingModel[[1]] %>% left_join(age_gender) %>% select(Component_1) %>% pull(), method="pearson")

cor.test(lowinterModel[[1]] %>% left_join(age_gender) %>% select(age) %>% pull(), lowinterModel[[1]] %>% left_join(age_gender) %>% select(Component_1) %>% pull(), method="pearson")

cor.test(uplingModel[[1]] %>% left_join(age_gender) %>% select(age) %>% pull(), uplingModel[[1]] %>% left_join(age_gender) %>% select(Component_1) %>% pull(), method="pearson")
cor.test(uplingModel[[1]] %>% left_join(age_gender) %>% select(age) %>% pull(), uplingModel[[1]] %>% left_join(age_gender) %>% select(Component_2) %>% pull(), method="pearson")

cor.test(upinterModel[[1]] %>% left_join(age_gender) %>% select(age) %>% pull(), upinterModel[[1]] %>% left_join(age_gender) %>% select(Component_1) %>% pull(), method="pearson")
cor.test(upinterModel[[1]] %>% left_join(age_gender) %>% select(age) %>% pull(), upinterModel[[1]] %>% left_join(age_gender) %>% select(Component_2) %>% pull(), method="pearson")

cor.test(salivaModel[[1]] %>% left_join(age_gender) %>% select(age) %>% pull(), salivaModel[[1]] %>% left_join(age_gender) %>% select(Component_1) %>% pull(), method="pearson")
cor.test(salivaModel[[1]] %>% left_join(age_gender) %>% select(age) %>% pull(), salivaModel[[1]] %>% left_join(age_gender) %>% select(Component_2) %>% pull(), method="pearson")
```

```{r more tests - bleeding on day 14}
cor.test(tongueModel[[1]] %>% left_join(rf_data %>% filter(day==14)) %>% select(Component_1) %>% pull(), tongueModel[[1]] %>% left_join(rf_data %>% filter(day==14)) %>% select(bomppercent) %>% pull(), method="pearson")
cor.test(tongueModel[[1]] %>% left_join(rf_data %>% filter(day==14)) %>% select(Component_2) %>% pull(), tongueModel[[1]] %>% left_join(rf_data %>% filter(day==14)) %>% select(bomppercent) %>% pull(), method="pearson")

cor.test(lowlingModel[[1]] %>% left_join(rf_data %>% filter(day==14)) %>% select(Component_1) %>% pull(), lowlingModel[[1]] %>% left_join(rf_data %>% filter(day==14)) %>% select(bomppercent) %>% pull(), method="pearson")

cor.test(lowinterModel[[1]] %>% left_join(rf_data %>% filter(day==14)) %>% select(Component_1) %>% pull(), lowinterModel[[1]] %>% left_join(rf_data %>% filter(day==14)) %>% select(bomppercent) %>% pull(), method="pearson")

cor.test(uplingModel[[1]] %>% left_join(rf_data %>% filter(day==14)) %>% select(Component_1) %>% pull(), uplingModel[[1]] %>% left_join(rf_data %>% filter(day==14)) %>% select(bomppercent) %>% pull(), method="pearson")
cor.test(uplingModel[[1]] %>% left_join(rf_data %>% filter(day==14)) %>% select(Component_2) %>% pull(), uplingModel[[1]] %>% left_join(rf_data %>% filter(day==14)) %>% select(bomppercent) %>% pull(), method="pearson")

cor.test(upinterModel[[1]] %>% left_join(rf_data %>% filter(day==14)) %>% select(Component_1) %>% pull(), upinterModel[[1]] %>% left_join(rf_data %>% filter(day==14)) %>% select(bomppercent) %>% pull(), method="pearson")
cor.test(upinterModel[[1]] %>% left_join(rf_data %>% filter(day==14)) %>% select(Component_2) %>% pull(), upinterModel[[1]] %>% left_join(rf_data %>% filter(day==14)) %>% select(bomppercent) %>% pull(), method="pearson")

cor.test(salivaModel[[1]] %>% left_join(rf_data %>% filter(day==14)) %>% select(Component_1) %>% pull(), salivaModel[[1]] %>% left_join(rf_data %>% filter(day==14)) %>% select(bomppercent) %>% pull(), method="pearson")
cor.test(salivaModel[[1]] %>% left_join(rf_data %>% filter(day==14)) %>% select(Component_2) %>% pull(), salivaModel[[1]] %>% left_join(rf_data %>% filter(day==14)) %>% select(bomppercent) %>% pull(), method="pearson")
```

```{r more tests - plaque on day 14}
cor.test(tongueModel[[1]] %>% left_join(rf_data %>% filter(day==14)) %>% select(Component_1) %>% pull(), tongueModel[[1]] %>% left_join(rf_data %>% filter(day==14)) %>% select(plaquepercent) %>% pull(), method="pearson")
cor.test(tongueModel[[1]] %>% left_join(rf_data %>% filter(day==14)) %>% select(Component_2) %>% pull(), tongueModel[[1]] %>% left_join(rf_data %>% filter(day==14)) %>% select(plaquepercent) %>% pull(), method="pearson")

cor.test(lowlingModel[[1]] %>% left_join(rf_data %>% filter(day==14)) %>% select(Component_1) %>% pull(), lowlingModel[[1]] %>% left_join(rf_data %>% filter(day==14)) %>% select(plaquepercent) %>% pull(), method="pearson")

cor.test(lowinterModel[[1]] %>% left_join(rf_data %>% filter(day==14)) %>% select(Component_1) %>% pull(), lowinterModel[[1]] %>% left_join(rf_data %>% filter(day==14)) %>% select(plaquepercent) %>% pull(), method="pearson")

cor.test(uplingModel[[1]] %>% left_join(rf_data %>% filter(day==14)) %>% select(Component_1) %>% pull(), uplingModel[[1]] %>% left_join(rf_data %>% filter(day==14)) %>% select(plaquepercent) %>% pull(), method="pearson")
cor.test(uplingModel[[1]] %>% left_join(rf_data %>% filter(day==14)) %>% select(Component_2) %>% pull(), uplingModel[[1]] %>% left_join(rf_data %>% filter(day==14)) %>% select(plaquepercent) %>% pull(), method="pearson")

cor.test(upinterModel[[1]] %>% left_join(rf_data %>% filter(day==14)) %>% select(Component_1) %>% pull(), upinterModel[[1]] %>% left_join(rf_data %>% filter(day==14)) %>% select(plaquepercent) %>% pull(), method="pearson")
cor.test(upinterModel[[1]] %>% left_join(rf_data %>% filter(day==14)) %>% select(Component_2) %>% pull(), upinterModel[[1]] %>% left_join(rf_data %>% filter(day==14)) %>% select(plaquepercent) %>% pull(), method="pearson")

cor.test(salivaModel[[1]] %>% left_join(rf_data %>% filter(day==14)) %>% select(Component_1) %>% pull(), salivaModel[[1]] %>% left_join(rf_data %>% filter(day==14)) %>% select(plaquepercent) %>% pull(), method="pearson")
cor.test(salivaModel[[1]] %>% left_join(rf_data %>% filter(day==14)) %>% select(Component_2) %>% pull(), salivaModel[[1]] %>% left_join(rf_data %>% filter(day==14)) %>% select(plaquepercent) %>% pull(), method="pearson")
```

```{r more tests - rf on day 9}
cor.test(tongueModel[[1]] %>% left_join(rf_data %>% filter(day==9)) %>% select(Component_1) %>% pull(), tongueModel[[1]] %>% left_join(rf_data %>% filter(day==9)) %>% select(Area_delta_R30) %>% pull(), method="pearson")
cor.test(tongueModel[[1]] %>% left_join(rf_data %>% filter(day==9)) %>% select(Component_2) %>% pull(), tongueModel[[1]] %>% left_join(rf_data %>% filter(day==9)) %>% select(Area_delta_R30) %>% pull(), method="pearson")

cor.test(lowlingModel[[1]] %>% left_join(rf_data %>% filter(day==9)) %>% select(Component_1) %>% pull(), lowlingModel[[1]] %>% left_join(rf_data %>% filter(day==9)) %>% select(Area_delta_R30) %>% pull(), method="pearson")

cor.test(lowinterModel[[1]] %>% left_join(rf_data %>% filter(day==9)) %>% select(Component_1) %>% pull(), lowinterModel[[1]] %>% left_join(rf_data %>% filter(day==9)) %>% select(Area_delta_R30) %>% pull(), method="pearson")

cor.test(uplingModel[[1]] %>% left_join(rf_data %>% filter(day==9)) %>% select(Component_1) %>% pull(), uplingModel[[1]] %>% left_join(rf_data %>% filter(day==9)) %>% select(Area_delta_R30) %>% pull(), method="pearson")
cor.test(uplingModel[[1]] %>% left_join(rf_data %>% filter(day==9)) %>% select(Component_2) %>% pull(), uplingModel[[1]] %>% left_join(rf_data %>% filter(day==9)) %>% select(Area_delta_R30) %>% pull(), method="pearson")

cor.test(upinterModel[[1]] %>% left_join(rf_data %>% filter(day==9)) %>% select(Component_1) %>% pull(), upinterModel[[1]] %>% left_join(rf_data %>% filter(day==9)) %>% select(Area_delta_R30) %>% pull(), method="pearson")
cor.test(upinterModel[[1]] %>% left_join(rf_data %>% filter(day==9)) %>% select(Component_2) %>% pull(), upinterModel[[1]] %>% left_join(rf_data %>% filter(day==9)) %>% select(Area_delta_R30) %>% pull(), method="pearson")

cor.test(salivaModel[[1]] %>% left_join(rf_data %>% filter(day==9)) %>% select(Component_1) %>% pull(), salivaModel[[1]] %>% left_join(rf_data %>% filter(day==9)) %>% select(Area_delta_R30) %>% pull(), method="pearson")
cor.test(salivaModel[[1]] %>% left_join(rf_data %>% filter(day==9)) %>% select(Component_2) %>% pull(), salivaModel[[1]] %>% left_join(rf_data %>% filter(day==9)) %>% select(Area_delta_R30) %>% pull(), method="pearson")
```

```{r tabulation of rf groups per subject group}
tongueSubjectClustering %>% select(group, RFgroup) %>% table()
lowlingSubjectClustering %>% select(group, RFgroup) %>% table()
lowinterSubjectClustering %>% select(group, RFgroup) %>% table()
uplingSubjectClustering %>% select(group, RFgroup) %>% table()
upinterSubjectClustering %>% select(group, RFgroup) %>% table()
salivaSubjectClustering %>% select(group, RFgroup) %>% table()

fisher.test(tongueSubjectClustering %>% select(group, RFgroup) %>% table())
```

```{r are the patterns also visible in the original data?}
checkRawData = function(df, model, subjectClustering, featureClustering){
  numSubjectGroups = max(subjectClustering$group)
  numFeatureGroups = max(featureClustering$group)
  
  plotlist = list()
  plotIndex = 1
  
  for(i in 1:numSubjectGroups){
    subjectGroup = subjectClustering %>% filter(group == i) %>% select(subject) %>% pull
    plotlist[[plotIndex]] = df %>% pivot_longer(-c(subject,timepoint)) %>% left_join(featureClustering, by=c("name"="asv")) %>% filter(subject %in% subjectGroup, group %in% 1:numFeatureGroups) %>% ggplot(aes(x=as.factor(timepoint), y=value, fill=as.factor(group))) + geom_boxplot() + ggtitle(paste0("Subject group ", i))
    plotIndex = plotIndex + 1
  }
  
  for(j in 1:numFeatureGroups){
    featureGroup = featureClustering %>% filter(group == j) %>% select(asv) %>% pull
    plotlist[[plotIndex]] = df %>% pivot_longer(-c(subject,timepoint)) %>% left_join(subjectClustering) %>% filter(name %in% featureGroup, group %in% 1:numSubjectGroups) %>% ggplot(aes(x=as.factor(timepoint), y=value, fill=as.factor(group))) + geom_boxplot() + ggtitle(paste0("Feature group ", j))
    plotIndex = plotIndex + 1
  }
  
  plotlist[[plotIndex]] = plotFeatureClustering(model, featureClustering, "Feature loadings")
  plotIndex = plotIndex + 1
  plotlist[[plotIndex]] = plotFeatureClustering_meta(model, featureClustering, "Feature loadings")
  plotIndex = plotIndex + 1
  plotlist[[plotIndex]] = plotSubjectClustering(model, subjectClustering, "Subject loadings")
  plotIndex = plotIndex + 1
  plotlist[[plotIndex]] = plotSubjectClustering_meta(model, subjectClustering, "Subject loadings")

  ggarrange(plotlist=plotlist)
}

checkRawData(microb_tongue_clr_long, tongueModel, tongueSubjectClustering, tongueFeatureClustering)
checkRawData(microb_lowling_clr_long, lowlingModel, lowlingSubjectClustering, lowlingFeatureClustering)
checkRawData(microb_lowinter_clr_long, lowinterModel, lowinterSubjectClustering, lowinterFeatureClustering)
checkRawData(microb_upling_clr_long, uplingModel, uplingSubjectClustering, uplingFeatureClustering)
checkRawData(microb_upinter_clr_long, upinterModel, upinterSubjectClustering, upinterFeatureClustering)
checkRawData(microb_saliva_clr_long, salivaModel, salivaSubjectClustering, salivaFeatureClustering)

df = metab_pqn_long
model = metabolomicsModel
subjectClustering = metabolomicsSubjectClustering
featureClustering = metabolomicsFeatureClustering

numSubjectGroups = max(subjectClustering$group)
numFeatureGroups = max(featureClustering$group)
  
plotlist = list()
plotIndex = 1
  
for(i in 1:numSubjectGroups){
  subjectGroup = subjectClustering %>% filter(group == i) %>% select(subject) %>% pull
  plotlist[[plotIndex]] = df %>% pivot_longer(-c(subject,timepoint)) %>% left_join(featureClustering, by=c("name"="BIOCHEMICAL")) %>% filter(subject %in% subjectGroup, group %in% 1:numFeatureGroups) %>% ggplot(aes(x=as.factor(timepoint), y=value, fill=as.factor(group))) + geom_boxplot() + ggtitle(paste0("Subject group ", i))
  plotIndex = plotIndex + 1
}
  
for(j in 1:numFeatureGroups){
  featureGroup = featureClustering %>% filter(group == j) %>% select(BIOCHEMICAL) %>% pull
  plotlist[[plotIndex]] = df %>% pivot_longer(-c(subject,timepoint)) %>% left_join(subjectClustering) %>% filter(name %in% featureGroup, group %in% 1:numSubjectGroups) %>% ggplot(aes(x=as.factor(timepoint), y=value, fill=as.factor(group))) + geom_boxplot() + ggtitle(paste0("Feature group ", j))
  plotIndex = plotIndex + 1
}

plotlist[[plotIndex]] = plotFeatureClustering(model, featureClustering, "Feature loadings")
plotIndex = plotIndex + 1
plotlist[[plotIndex]] = featureClustering %>% ggplot(aes(x=Component_1,y=Component_2,col=as.factor(SUPER_PATHWAY))) + geom_point() + geom_vline(xintercept=0, linetype=2) + geom_hline(yintercept=0, linetype=2) + ggtitle(title)
plotIndex = plotIndex + 1
plotlist[[plotIndex]] = plotSubjectClustering(model, subjectClustering, "Subject loadings")
plotIndex = plotIndex + 1
plotlist[[plotIndex]] = plotSubjectClustering_meta(metabolomicsModel, metabolomicsSubjectClustering, "Subject loadings")

ggarrange(plotlist=plotlist)
```

```{r checking grouping of responders}
groupingTable = tongueSubjectClustering %>% select(subject, RFgroup, group) %>% mutate(tongueGroup = group) %>% select(-group) %>% full_join(lowlingSubjectClustering %>% select(subject, group) %>% mutate(lowlingGroup = group) %>% select(-group)) %>% full_join(lowinterSubjectClustering %>% select(subject, group) %>% mutate(lowinterGroup = group) %>% select(-group)) %>% full_join(uplingSubjectClustering %>% select(subject,group) %>% mutate(uplingGroup = group) %>% select(-group)) %>% full_join(upinterSubjectClustering %>% select(subject,group) %>% mutate(upinterGroup = group) %>% select(-group)) %>% full_join(salivaSubjectClustering %>% select(subject,group) %>% mutate(salivaGroup = group) %>% select(-group)) %>% full_join(metabolomicsSubjectClustering %>% select(subject,group) %>% mutate(metabolomicsGroup=group) %>% select(-group)) %>% arrange(RFgroup)
```